### PR TITLE
fix: start the LS with the board specific settings

### LINKED ISSUE #1029: Language Server (autocomplete) not using menu settings
### Describe the problem

The autocomplete and variable info popups find info corresponding to the Tools menu configuration options at their defaults, even when the user has changed them to a different configuration.  The tools menu config can cause the build process to use a different set of defines, changing which code is actually compiled.  The IDE should cause the language server to always operate with settings from the currently selected menu config, but today it appears to be always using the menu defaults regardless of what has actually been selected in those menus.

### To reproduce

Using Arduino IDE 2.0.0-rc7.

1: add https://www.pjrc.com/teensy/td_156/package_teensy_index.json to additional board manager URLs in File > Preferences

2: in boards manager, search for "teensy" and install Teensy package 1.56.1

3: set the current board to Tools > Board > Teensy > Teensy 4.1

4: open or type any program with Serial, such as
``` c
void setup() {
  Serial.begin();
}

void loop() {
}
```

5: hover your mouse over "Serial".  A popup will appear telling you the type is "class usb_serial_class".
image

6: click Tools > USB Type and change the configuration to "RawHID"
image

7: again hover your mouse over "Serial".  The popup will reappear, incorrectly telling you the type is still "class usb_serial_class".
image

8: right click Serial and select "Go To Definition".  A new tab will open, showing the wrong definition which is not compiled cause CDC_DATA_INTERFACE and CDC_STATUS_INTERFACE are not defined when USB Type RawHID is selected.
image

### Expected behavior

When USB Type is set to RawHID, the Serial object is defined as "usb_seremu_class Serial" at line 75 in usb_inst.cpp.

image

Changing the menu configuration alters the compiler build flags, causing completely different code to be compiled.  The IDE should always configure the Language Server with the defines or other build flags from the menu configuration.

### Arduino IDE version

2.0.0-rc7

### Operating system

Linux

### Operating system version

Ubuntu 20.04

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

The Arduino Language features must incorporate the settings of the selected board.

### Change description

From now on, the IDE2 starts the LS with the FQBN decorated with the settings. Open the DevTools and check the console if you're interested:

```
INFO Starting language server: teensy:avr:teensy41:usb=serial,speed=600,opt=o2std,keys=en-us
```

Also, from now on, the LS restarts when the user changes the board settings of the currently running LS.

Steps to verify:
 - See the excellent instructions from #1029.
 - Also, the LS updates if you change `Tools` > `USB Type`  from `Serial` to `Raw HID` and vice versa. This can be verified with the [`textDocument/hover`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover) in the editor.

In action:

https://user-images.githubusercontent.com/1405703/211559452-b4d9cd03-4856-444f-80b4-af0ff27cd157.mp4

### Other information

Closes #1029

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: arduino-ide-extension/src/common/protocol/boards-service.ts [hunk 1]
```diff
@@ -623,3 +623,27 @@ export namespace Board {
     }));
   }
 }
+
+/**
+ * Throws an error is the `fqbn` argument is not sanitized. A sanitized FQBN has the `VENDOR:ARCHITECTURE:BOARD_ID` construct.
+ */
```
Comment (AlbyIanna) [inline arduino-ide-extension/src/common/protocol/boards-service.ts:629]:
```suggestion
/**
 * Throws an error if the `fqbn` argument is not sanitized. A sanitized FQBN has the `VENDOR:ARCHITECTURE:BOARD_ID` construct.
 */
```

**Review by AlbyIanna — APPROVED** [review]
It works as expected for me. I just left a remark about a little typo in a comment

File: arduino-ide-extension/src/common/protocol/boards-service.ts (hunk 1 above)
Comment (kittaakos) [reply arduino-ide-extension/src/common/protocol/boards-service.ts]: Thank you!

**Review by per1234 — APPROVED** [review]
Thanks Akos!
