### PR TITLE
Set `XDG_CONFIG_HOME` env on Linux when not set.

### LINKED ISSUE #394: Starting IDE creates "undefined" folder in current directory
**Describe the bug**
It is more an oddity than a bug.
Whenever I start the IDE the program creates a folder called "undefined" in my home directory.  This folder contains only one folder called "Arduino IDE" which contains logs of the IDE. I think it's good that the logs are saved in an easy to find location. But all the time I'm looking into my home-folder the "undefined" folder kind of confuses me. 

**To Reproduce**
1. Start the IDE
2. go to home folder
3. be happy with "undefined" folder

**Expected behavior**
Just giving it a more precise name would make me happy.

**Screenshots**
screenshot

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04.2 LTS
 - Version: 2.0.0-beta.7

**Additional context**
As already mentioned in arduino/arduino-ide#110 it is not perfectly documented how to install the IDE correctly, so i guess it could also be an error of me in the installation process.  In my point of view I went a straight forward way, downloading the newest IDE, unzipping the contents and copying the files to /opt/
To have it listed in the applications menu of Ubuntu I created the file `Arduino 2.0 (beta).desktop` in `~/.local/share/applications` with the following content:
``` 
[Desktop Entry]
Type=Application
# desktop entry spec version
Version=6.4.2
Name=Arduino 2.0 (beta)
Comment=Arduino IDE 2.0 beta
Exec=/opt/arduino-ide_2.0.0-beta.07/arduino-ide
Icon=/opt/arduino-1.8.13/lib/arduino.png
MimeType=image/svg+xml;
Terminal=false
Categories=Development
X-Desktop-File-Install-Version=0.24
```
It is mostly a copy of another .desktop file in the directory.

Now starting the IDE results in generating the undefined-folder. Everything else works perfectly.

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

Set the `XDG_CONFIG_HOME` env on Linux when not set. Otherwise, `node-log-rotate` creates a folder with the `undefined` name.

### Change description

Patched the patched `main.js` for the Theia backend. 🤦 

### Other information

Closes #394.

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: electron/build/patch/backend/main.js [hunk 1]
```diff
@@ -1,4 +1,18 @@
 // @ts-check
+
+// Patch for on Linux when `XDG_CONFIG_HOME` is not available, `node-log-rotate` creates the folder with `undefined` name.
```
Comment (kittaakos) [inline electron/build/patch/backend/main.js:3]: remove `on`

**Review by umbynos — APPROVED** [review]

**Comment by umbynos** [comment]
This seems to be solved. The log are created now under `~/.config` dir

**Comment by kittaakos** [comment]
Great news, thank you for the verification. I am merging this.
