### PR TITLE
#1084, #1156 Various library/platform index update fixes

### LINKED ISSUE #1084: IDE is non-functional if package index can't be loaded
### Describe the problem

[Package indexes](https://arduino.github.io/arduino-cli/dev/package_index_json-specification/) are used by the Arduino Boards Manager system to track the [Arduino boards platforms](https://arduino.github.io/arduino-cli/dev/platform-specification/) that are available for installation.

These come from two types of sources:

- The official [primary package index](https://downloads.arduino.cc/packages/package_index.json)
- URLs specified by the user via the "**Additional Boards Manager URLs**" field of the IDE's "**Preferences**" dialog

The package indexes are downloaded from these URLs by Arduino IDE 2.x on startup.

🐛 Under the following conditions, the IDE is non-functional:

- A package index cannot be downloaded from its URL
- The package index is not already present in `directories.data`

### To reproduce

1. Select **File > Preferences...** from the Arduino IDE menus.
1. Add the following to the "**Additional Boards Manager URLs**" field:
   ```text
   https://downloads.arduino.cc/packages/package_nonexistent_index.json
   ```
   **ⓘ** The issue is not specific to this URL. Any URL that does not provide a package index URL download can be used.
1. Click the <kbd>**OK**</kbd> button.
1. Select **File > Quit** from the Arduino IDE menus.
1. Start the Arduino IDE.
1. Open the "Board Selector" menus.
   🐛 No boards are shown.
1. Open the **Tools** menu.
   🐛 There is no "**Boards**" menu.
1. Open the "**Boards Manager**" view.
   🐛 The view is empty, not even showing the currently installed platforms.
1. Open the "**Library Manager**" view.
   🐛 The view is empty.

🐛 The only way for the user to identify the problem is searching through the logs.

### Expected behavior

Clearly communicate to the user that there was a problem with downloading the package index.

It would probably also make sense to retain general functionality of the Arduino IDE (though of course the Boards Manager functionality that relies on the missing package index in particular will not be available).

### Arduino IDE version

2.0.0-rc7-snapshot-a715da3

### Operating system

Windows

### Operating system version

10

### Additional context

I bisected the issue to https://github.com/arduino/arduino-ide/commit/4c55807392b3b724e2c5912280c621f9ed8db5e6 (does not occur with the build from https://github.com/arduino/arduino-ide/commit/cb50d3a70d1dc34d46bb1373f9aa4678f14f7133)

---

The logs contain the following:

```text
root ERROR Uncaught Exception:
root ERROR Error: 13 INTERNAL: Error downloading index 'https://downloads.arduino.cc/packages/package_nonexistent_index.json': Server responded with: 404 Not Found
    at Object.callErrorFromStatus (C:\ide 2\tip\48-a715da3\resources\app\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\ide 2\tip\48-a715da3\resources\app\node_modules\@grpc\grpc-js\build\src\client.js:349:49)
    at Object.onReceiveStatus (C:\ide 2\tip\48-a715da3\resources\app\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
    at C:\ide 2\tip\48-a715da3\resources\app\node_modules\@grpc\grpc-js\build\src\call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

---

Even though it is most likely to occur with package indexes provided by via the "**Additional Boards Manager URLs**" preference (whether by user error, no connection to Internet, or transient network outage on the server), it does also occur even with the primary package index so long as the conditions described previously are present.

---

Originally reported at https://github.com/arduino/arduino-ide/issues/1036#issuecomment-1152531289

I mistakenly claimed that issue had been fixed by https://github.com/arduino/arduino-ide/pull/1045 because I did not realize at that time that the package index's absence from `directories.data` was a required condition to reproduce it.

---

Related:

- https://forum.arduino.cc/t/arduino-2-0-0-rc-7-no-board-manager-or-library-manager/1004131/6
- https://forum.arduino.cc/t/ide-2-0-0-rc8-missing-tools-board-and-other-menus/1007606

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### LINKED ISSUE #1156: Only package indexes should updated after changing the "Additional Boards Manager URL" preference.
### Describe the problem

Originally reported [here](https://github.com/arduino/arduino-ide/pull/1132#pullrequestreview-1028527692):

> I notice that [the Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) is updated along with the package indexes after a change to the "**Additional Boards Manager URLs**" preference.
> 
> It seems a bit arbitrary to me since there is no reason to think a change to this Boards Manager-specific preference is an indication that the user is planning to use Library Manager.
>
>I think that, for most users, just having a single library index update on startup will be sufficient. That might be problematic if a user leaves the IDE open permanently, but I think that would be a very rare usage pattern. Perhaps a periodic update of all indexes could be implemented at some point as part of the updatable platform and library notification system.

### To reproduce

> 1. Select **File > Preferences** from the Arduino IDE menus.
> 2. Change the "**Additional Boards Manager URL**" preference by either adding or removing URLs.
> 3. Click the **OK** button.
> 4. Watch the index download notifications. They include "**Downloading index: library_index.json.gz**".
> 
> From the gRPC logs, it appears that a [`cc.arduino.cli.commands.v1.ArduinoCoreService/UpdateLibrariesIndex` request](https://arduino.github.io/arduino-cli/dev/rpc/commands/#updatelibrariesindexrequest) is being sent in addition to the expected `UpdateIndex` for the package indexes.
> 
> ```
> daemon INFO 25 CALLED: /cc.arduino.cli.commands.v1.ArduinoCoreService/UpdateIndex STREAM_RESP
> 26 CALLED: /cc.arduino.cli.commands.v1.ArduinoCoreService/UpdateLibrariesIndex STREAM_RESP
> ```

### Expected behavior

> Only package indexes are updated after changing the "**Additional Boards Manager URLs**" preference.

### Arduino IDE version

`HEAD` of the `main`

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

> 2.0.0-rc8-snapshot-24cc9f1 (tester build for [a2bec12](https://github.com/arduino/arduino-ide/commit/a2bec1264545def494975fedecece79d185f47b8))

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

 - IDE2 should start when an invalid 3rd party URL is set and `#directories/data` is empty. (#1084)
 - IDE2 should not run the library index update when on 3rd party URL changes from _Settings_. (#1156)
 - IDE2 does not automatically update the platform/library indexes after the app starts but only runs the index update if the last update was later than 4 hours. If `arduino.checkForUpdates` is `false` no automatic index update will run.
 - Users can manually trigger a package/library/both index updates with a command.

### Other information

Closes #1084
Closes #1156

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: arduino-ide-extension/src/browser/contributions/update-indexes.ts [hunk 1]
```diff
@@ -0,0 +1,193 @@
...
+        'arduino/updateIndexes/updateIndexes',
+        'Update Indexes'
+      ),
+      category: 'Arduino',
+    };
+    export const UPDATE_PLATFORM_INDEX: Command & { label: string } = {
+      id: 'arduino-update-platform-index',
+      label: nls.localize(
+        'arduino/updateIndexes/updatePlatformIndex',
+        'Update Platform Index'
```
Comment (per1234) [inline arduino-ide-extension/src/browser/contributions/update-indexes.ts:180]:
```suggestion
        'Update Package Index'
```

"Package index" is the correct terminology here:

https://arduino.github.io/arduino-cli/dev/package_index_json-specification/

A package is a container for platforms and tools, so "platform index" is not a very accurate description of this thing. Since tools are usually only an asset for the platforms in the index, users are typically focused on platforms when thinking of a package index. However, any platform can reference a tool dependency from any other package, so a package index may serve solely for the distribution of tools ([example](https://forum.arduino.cc/t/error-during-installation-index-error-could-not-find-referenced-tool/1036410)).

In the primary user interface, package indexes may also be referred to by the more user understandable "Boards Manager URL" term. In this case of the advanced interface, and especially since there is no established "Library Manager URL" term to use for the parallel library index command, I think "package index" is the right choice.

**Review by per1234 — CHANGES_REQUESTED** [review]

File: arduino-ide-extension/src/browser/contributions/update-indexes.ts (hunk 1 above)
Comment (kittaakos) [reply arduino-ide-extension/src/browser/contributions/update-indexes.ts]: Screen Shot 2022-10-04 at 10 17 56

**Review by AlbyIanna — APPROVED** [review]
Haven't tested it thoroughly but code looks fine to me. Green light 🟢
