### PR TITLE
fix: show board info based on the selected port

### LINKED ISSUE #1435: Show board serial number from `Tools` > `Get Board Info`
### Describe the request

Arduino IDE 1.x can show the board info such as board number, VID/PID, and serial number from the `Tools` > `Get Board Info` The serial number is missing from IDE2.

IDE 1.x
b11cac7a-bdf5-4755-a78e-fe3ae8401815 (1)

IDE2:
Screen Shot 2022-09-15 at 08 24 11

The serial number can be acquired from the `Port#properties` See #1335.

### Describe the current behavior

IDE2 does not show the SN of the board.

### Arduino IDE version

2.0.0

### Operating system

macOS

### Operating system version

12.5.1

### Additional context

Related:

- https://github.com/arduino/arduino-ide/pull/276
- https://forum.arduino.cc/t/get-board-info-missing-serial-number/1055380

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

### LINKED ISSUE #1489: Incorrect output from `Tools` > `Get Board Info`
### Describe the problem

The _Tools > Get Board Info_ option does not correctly identify the board on the selected port. Instead it provides information based on the selected board core (i.e. _Tools > Board_), which I think is far less useful.

### To reproduce

1. Select _Tools > Board > Arduino AVR Boards > Arduino UNO_.
2. Open _Tools > Port_ and select any port that does **not** have an Arduino UNO connected.
3. Select _Tools > Get Board Info_

The output will be based on the selected board, not on what (if anything) is connected to the selected port.

Here an Arduino Mega 2560 Rev3 is on the selected port (which is correctly identified in the port menu):

image

> Unlike IDE 1.x, SN is not included. This feature has been requested (https://github.com/arduino/arduino-ide/issues/1435).

But _Tools > Get Board Info_ incorrectly identifies it as an Arduino UNO.

Screenshot 2022-09-23 at 13 31 42

### Expected behavior

* **If a board can be identified on the port:** Provide information about the board.
* **If no board could be identified:** Show an error message, e.g. <samp>Please select a port to obtain board info</samp> or <samp>Native serial port, can't obtain info</samp>

Example output from IDE 1.8.19 for an Arduino Mega 2560 on the port and Arduino UNO as the selected board:

Screenshot 2022-09-23 at 13 30 38

### Arduino IDE version

2.0.0-nightly-20220922

### Operating system

macOS

### Operating system version

12.4 (21F79)

### Additional context

Related:

- https://github.com/arduino/arduino-ide/issues/1435

---

Additional reports:

- https://github.com/arduino/arduino-ide/issues/1647
- https://forum.arduino.cc/t/ide-and-avrdude-command-line/1070148/12

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

As requested in #1435, IDE2 shows the board info based on the `Tools` > `Port` and *not* `Tools` > `Board`.
This PR makes the board's serial number (SN) available via the board details.

### Change description

Expected behavioral change:

 - IDE shows the SN if available.
 - IDE shows the `Network port, can't obtain info.` message when a  network port is selected.
 - IDE shows the `Native serial port, can't obtain info.` message when no `matching_boards` can be found for the currently selected port. For example, I installed the core for ESP8266MOD, compiled against the `NodeMCU 0.9 (ESP-12 Module)` board on the `/dev/cu.usbserial-0001` `serial` port, compile upload works, but as this board is not recognized as the `matching_boards` of a port (`board list --format json`), it cannot show the details.

Examples:

https://user-images.githubusercontent.com/1405703/211012954-900eafac-8581-4051-9d41-3f9b83b4af91.mp4

https://user-images.githubusercontent.com/1405703/211013035-82aa3d4c-1be2-4f35-ad34-3d3d6fe8f900.mp4

Locally discovered boards for the examples:

```json
[
  {
    "matching_boards": [
      {
        "name": "Arduino MKR1000",
        "fqbn": "arduino:samd:mkr1000"
      }
    ],
    "port": {
      "address": "192.168.0.104",
      "label": "Arduino at 192.168.0.104",
      "protocol": "network",
      "protocol_label": "Network Port",
      "properties": {
        ".": "mkr1000",
        "auth_upload": "yes",
        "board": "mkr1000",
        "hostname": "Arduino.local.",
        "port": "65280",
        "ssh_upload": "no",
        "tcp_check": "no"
      }
    }
  },
  {
    "matching_boards": [
      {
        "name": "Arduino Uno",
        "fqbn": "arduino:avr:uno"
      }
    ],
    "port": {
      "address": "/dev/cu.usbmodem14401",
      "label": "/dev/cu.usbmodem14401",
      "protocol": "serial",
      "protocol_label": "Serial Port (USB)",
      "properties": {
        "pid": "0x0043",
        "serialNumber": "551313237373514130C1",
        "vid": "0x2341"
      }
    }
  },
  {
    "port": {
      "address": "/dev/cu.BLTH",
      "label": "/dev/cu.BLTH",
      "protocol": "serial",
      "protocol_label": "Serial Port"
    }
  },
  {
    "port": {
      "address": "/dev/cu.Bluetooth-Incoming-Port",
      "label": "/dev/cu.Bluetooth-Incoming-Port",
      "protocol": "serial",
      "protocol_label": "Serial Port"
    }
  },
  {
    "port": {
      "address": "/dev/cu.usbserial-0001",
      "label": "/dev/cu.usbserial-0001",
      "protocol": "serial",
      "protocol_label": "Serial Port (USB)",
      "properties": {
        "pid": "0xEA60",
        "serialNumber": "0001",
        "vid": "0x10C4"
      }
    }
  },
  {
    "port": {
      "address": "/dev/cu.SLAB_USBtoUART",
      "label": "/dev/cu.SLAB_USBtoUART",
      "protocol": "serial",
      "protocol_label": "Serial Port (USB)",
      "properties": {
        "pid": "0xEA60",
        "serialNumber": "0001",
        "vid": "0x10C4"
      }
    }
  },
  {
    "matching_boards": [
      {
        "name": "Arduino MKR1000",
        "fqbn": "arduino:samd:mkr1000"
      }
    ],
    "port": {
      "address": "/dev/cu.usbmodem14301",
      "label": "/dev/cu.usbmodem14301",
      "protocol": "serial",
      "protocol_label": "Serial Port (USB)",
      "properties": {
        "pid": "0x804E",
        "serialNumber": "94A3397C5150435437202020FF150838",
        "vid": "0x2341"
      }
    }
  }
]
```

 - MKR1000 on serial,
 - MKR1000 on network,
 - UNO on serial,
 - ESP8266MOD on serial

### Other information

Closes #1489
Closes #1435

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: arduino-ide-extension/src/browser/contributions/board-selection.ts [hunk 1]
```diff
@@ -79,22 +82,80 @@ export class BoardSelection extends SketchContribution {
...
+        );
+        // IDE 1.x show this when cannot identify for example a ESP8266MOD although compile and upload works
+        if (!boardListOnSelectedPort.length) {
+          this.messageService.info(
+            nls.localize(
+              'arduino/board/noNativeSerialPort',
+              "Native serial port, can't obtain info."
+            )
+          );
+          return;
```
Comment (per1234) [inline arduino-ide-extension/src/browser/contributions/board-selection.ts:122]: There are three possible cases:

- identified port
- unidentified port
- native port

An example of all three is shown here:

```text
$ arduino-cli board list --format json
[
  {
    "port": {
      "address": "/dev/ttyUSB0",
      "label": "/dev/ttyUSB0",
      "protocol": "serial",
      "protocol_label": "Serial Port (USB)",
      "properties": {
        "pid": "0x6001",
        "serialNumber": "AB0P8H9K",
        "vid": "0x0403"
      }
    }
  },
  {
    "matching_boards": [
      {
        "name": "Arduino Uno",
        "fqbn": "arduino:avr:uno"
      }
    ],
    "port": {
      "address": "/dev/ttyACM0",
      "label": "/dev/ttyACM0",
      "protocol": "serial",
      "protocol_label": "Serial Port (USB)",
      "properties": {
        "pid": "0x0043",
        "serialNumber": "95032303537351D0F001",
        "vid": "0x2341"
      }
    }
  },
  {
    "port": {
      "address": "/dev/ttyS4",
      "label": "/dev/ttyS4",
      "protocol": "serial",
      "protocol_label": "Serial Port"
    }
  }
]
```

## Identified

`/dev/ttyACM0` is an identified port:

**Arduino IDE 1.x**

image

**Arduino IDE 2.x**

image

🙂 Arduino IDE 2.x behavior matches 1.x

## Unidentified

`/dev/ttyUSB0` is an unidentified port (it is a [classic **Nano**](https://store.arduino.cc/products/arduino-nano), which uses the manufacturer provided VID/PID pair of its general purpose FTDI 232RL USB chip, and thus can't be identified as a specific board):

**Arduino IDE 1.x**

image

**Arduino IDE 2.x**

image

🐛 Arduino IDE 2.x behavior does not match 1.x

The behavior of the current PR code is problematic for two reasons:

- It is incorrect to call `/dev/ttyUSB0` a "native port".
- It makes it so the VID and PID (which is valuable information for support/troubleshooting) can not be determined.

## Native

`/dev/ttyS4` is a native port:

**Arduino IDE 1.x**

image

**Arduino IDE 2.x**

image

🙂 Arduino IDE 2.x behavior matches 1.x

**Review by per1234 — CHANGES_REQUESTED** [review]

**Comment by kittaakos** [comment]
Thank you for the review, Per.

I pushed the requested changes. Please review.

I have a few questions and remarks:
 - I do not have a classic Nano board; hence I could not reproduce the behavior with an attached board.
 - I mocked the `board list --watch format json` response of the CLI based on your `board list` output, and it works like this in IDE2 from the PR:
    Screen Shot 2023-01-09 at 08 58 05
- How can any client of the CLI distinguish between serial and native serial ports:

```json
{
    "port": {
      "address": "/dev/ttyUSB0",
      "label": "/dev/ttyUSB0",
      "protocol": "serial",
      "protocol_label": "Serial Port (USB)",
      "properties": {
        "pid": "0x6001",
        "serialNumber": "AB0P8H9K",
        "vid": "0x0403"
      }
    }
  }
```

```json
  {
    "port": {
      "address": "/dev/ttyS4",
      "label": "/dev/ttyS4",
      "protocol": "serial",
      "protocol_label": "Serial Port"
    }
  }
```

 - Currently, IDE2 shows an unknown board for a port if the `protocol` is `'serial'` and the `matching_boards` is not empty or `'vid'` and `'pid'` is available from the `port#properties`. Is this the correct approach?
 - For the unidentified board, the SN is available: `AB0P8H9K`. Is this correct to show: `"Upload any sketch to obtain it."`? Thanks

**Comment by kittaakos** [comment]
> I have a few questions
> * How can any client of the CLI distinguish between serial and native serial ports:
> * Is this correct to show: `"Upload any sketch to obtain it."`?


IDE2 will consider a port a non-serial if:
 - The `port` `protocol` is `'serial'`, AND
 - The VID+PID is available from `port#properties`

----

From [@cmaglie](https://github.com/cmaglie):
 - before USB, the Serial ports were embedded in the PC. You'll get COM1 and COM2 usually, and you connected them using a 9 pin D-SUB connector this is what the IDE Java calls "native" port, because it's something that is embedded in the PC. It doesn't have any USB VID/PID, so nothing can be told about what you connect to that port
     image (3)
 - so fact 1. if you don't have VID/PID than it's a "native" port
 - after some times the USB standard got traction and the old serial ports have been replaced by USB-2-serial converters: you had these cables where one side was USB and the other was 9-pin D-SUB. Actually the USB connection was converted to Serial, but in this case the USB VID/PID are fixed, and are those of the chip mounted on the cable. This is the case where that Per calls "unidentified". you have VID/PID but it's the VID/PID of the "converter"
 - finally, we got the modern microcontrollers that have direct USB connection, so they can "emulate" an USB-2-serial cable... in this case each microcontoller can send arbitrary VID/PID, because there is no more the real convert cable, it's emulated, so each board can have his unique VID/PID. This is what Per calls "identified" port.

**Review by per1234 — CHANGES_REQUESTED** [review]
I believe the notification shown when no board is selected is an artifact from the old system where the information was sourced from the board definition.

It seems to me that the only requirement now is for a port to be selected, since the information is gathered from the port and the board definition is not used at all.

## To reproduce

1. Select **File > Quit** from the Arduino IDE menus if it is running
1. Rename or delete (:warning: cautiously) the following folder to produce the condition of not having a board selected:
   - Windows:
     ```
     C:\Users\<user name>\AppData\Roaming\arduino-ide
     ```
   - Linux:
     ```
     ~/.config/arduino-ide
     ```
   - macOS:
     ```
     ~/Library/Application Support/arduino-ide
     ```
1. Start Arduino IDE.
1. Select a port from the **Tools > Port** menu in Arduino IDE.
1. Select **Tools > Get Board Info** from the Arduino IDE menus.

🐛 An inappropriate notification is shown:

> **Please select a board to obtain board info.**

🐛 The "**Board Info**" dialog does not open.

File: arduino-ide-extension/src/browser/contributions/board-selection.ts [hunk 2]
```diff
@@ -79,22 +80,83 @@ export class BoardSelection extends SketchContribution {
...
+        // IDE 1.x does not support network ports
+        if (selectedPort.protocol === 'network') {
+          this.messageService.info(
+            nls.localize(
+              'arduino/board/noNetworkPort',
+              "Network port, can't obtain info."
+            )
+          );
+          return;
+        }
```
Comment (per1234) [inline arduino-ide-extension/src/browser/contributions/board-selection.ts:94]: I'm thinking this should be generalized to `if (selectedPort.protocol !== 'serial')`, with the notification text changed to something like "Non-serial port, can't obtain info".

We must keep in mind that ports can now have any arbitrary protocol instead of it only being `serial` and `network` as was the case for Arduino IDE 2.x. If the "Board Info" system is not able to correctly handle ports of arbitrary protocols, then they should be explicitly disabled.

For example, if I connect a Teensy board and select the port from the "**teensy ports**" section of the **Tools > Port** menu, when I select **Tools > Get Board Info**, Arduino IDE shows the incorrect notification:

> **Native serial port, can't obtain info.**

**Review by per1234 — CHANGES_REQUESTED** [review]

File: arduino-ide-extension/src/browser/contributions/board-selection.ts [hunk 3]
```diff
@@ -79,22 +80,83 @@ export class BoardSelection extends SketchContribution {
...
+          !!s ? s : '(null)';
+        const readProperty = (property: string, port: Port) =>
+          falsyToNullString(port.properties?.[property]);
+        const BN =
+          board?.name ??
+          nls.localize('arduino/board/unknownBoard', 'Unknown board');
+        const VID = readProperty('vid', port);
+        const PID = readProperty('pid', port);
+        const SN = board
+          ? readProperty('serialNumber', port)
```
Comment (per1234) [inline arduino-ide-extension/src/browser/contributions/board-selection.ts:142]: >For the unidentified board, the SN is available: AB0P8H9K. Is this correct to show: "Upload any sketch to obtain it."?

No. If the port has a `serialNumber` property, that should always be shown in the"**SN**" field of the "**Board Info**" dialog.

The board might only be unidentified because the platform is not installed (in combination with no "builder API" access in the case of official boards, as would be the case if the computer isn't connected to the Internet).

**Review by per1234 — CHANGES_REQUESTED** [review]

**Comment by kittaakos** [comment]
Could you please take another look, Per?

File: arduino-ide-extension/src/common/protocol/boards-service.ts [hunk 4]
```diff
@@ -647,3 +648,127 @@ export function sanitizeFqbn(fqbn: string | undefined): string | undefined {
...
+ * The returned promise resolves to a `BoardInfo` if available to show in the UI or an info message explaining why showing the board info is not possible.
+ */
+export async function getBoardInfo(
+  boardsConfig: BoardConfig,
+  availablePorts: MaybePromise<AvailablePorts>
+): Promise<BoardInfo | string> {
+  const { selectedBoard, selectedPort } = boardsConfig;
+  if (!selectedBoard) {
+    return selectBoardForInfo;
+  }
```
Comment (per1234) [inline arduino-ide-extension/src/common/protocol/boards-service.ts:716]: Is there a reason having a board selected is required? I questioned this in my previous review, which gives more info:

https://github.com/arduino/arduino-ide/pull/1803#pullrequestreview-1252844000

File: arduino-ide-extension/src/common/protocol/boards-service.ts [hunk 5]
```diff
@@ -647,3 +648,127 @@ export function sanitizeFqbn(fqbn: string | undefined): string | undefined {
...
+  if (!selectedBoard.fqbn) {
+    return platformMissing(selectedBoard.name);
+  }
```
Comment (per1234) [inline arduino-ide-extension/src/common/protocol/boards-service.ts:719]: I have [the same doubt](https://github.com/arduino/arduino-ide/pull/1803#pullrequestreview-1252844000) about this one. It seems to me that the only thing required is a port selection.

**Review by per1234 — CHANGES_REQUESTED** [review]

File: arduino-ide-extension/src/common/protocol/boards-service.ts (hunk 4 above)
Comment (kittaakos) [reply arduino-ide-extension/src/common/protocol/boards-service.ts:716]: In IDE2, selecting a port without a board is impossible.

Comment (per1234) [reply arduino-ide-extension/src/common/protocol/boards-service.ts:716]: It can be done by following the instructions I provide at https://github.com/arduino/arduino-ide/pull/1803#pullrequestreview-1252844000:

image

Comment (kittaakos) [reply arduino-ide-extension/src/common/protocol/boards-service.ts:716]: Yes, you're right. Thanks!

Comment (kittaakos) [reply arduino-ide-extension/src/common/protocol/boards-service.ts]: It's nice that you take the time to look into the code. You're a great help to me!

I have updated the PR as you asked me to. Please check again. Thanks!

**Review by per1234 — APPROVED** [review]
Thanks Akos!
