### PR TITLE
fix: flawed timing issue when opening editors

### LINKED ISSUE #1612: First time load of project with many files very slow with "the editor has not shown up in time" errors
### Describe the problem

We have a project that has 50+ .cpp and .h files. The first time you load this project, the 2.0 IDE is doing some kind of check on the files and slowly loads them one at a time in the IDE file tabs. This does not occur the next time the project is opened. The load takes several minutes. The second time through, it is still slow, but less than 30 seconds.

[arduino ide boot log 5.txt](https://github.com/arduino/arduino-ide/files/9913865/arduino.ide.boot.log.5.txt)

### To reproduce

Go to this repo, download the project, and try to load it into the 2.0 IDE
https://github.com/DCC-EX/CommandStation-EX

### Expected behavior

I would expect it to load much faster and not have a 5 second timeout for every file.

### Arduino IDE version

2.02 nightly 20221030

### Operating system

Windows

### Operating system version

Windows 11

### Additional context

boot log included above

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

This PR is to fix the flawed timing issue when opening editors.

### Change description

 - From now on, the editor widget open promise resolution does not rely on internal Theia events but solely on @phosphor's `isAttached`/`isVisible` properties. The editor widget promise resolves with the next task after a navigation frame so the browser can render the widget.
 - Generalized the invalid sketch name error handling and removed the CLI error messaging parsing logic due to arduino/arduino-cli#1968.

### Other information

For the testing, please use the [1612-sketches.zip](https://github.com/arduino/arduino-ide/files/9961315/1612-sketches.zip) archive. (However, you're allowed to use your own setup.)

`1612-sketches.zip`:

```
.
├── invalid-sketches
│   ├── Bar
│   │   └── xxx.ino
│   └── foo
│       └── Foo.ino
└── valid-sketches
    └── Errors1234567
        ├── CTab.c
        ├── CppTab.cpp
        ├── Errors1234567.ino
        ├── HTab.h
        ├── InoTab.ino
        └── src
            └── HFile.h

6 directories, 8 files
```

Expected behavior:
 - Editors open quickly for the first time (#1612).
    - Start the valid sketch with multiple files: it opens "quickly". At least the performance loss mentioned in. #1612 is OK.
        ```
        ./Arduino\ IDE.app/Contents/MacOS/Arduino\ IDE ./1612-sketches/valid-sketches/Errors1234567/
        ```
 - No regression with #1563
    - After opening an invalid sketch, IDE2 prompts a sketch move
    - The fallback sketch editor is already opened in IDE2 when the modal dialog prompts the move (this is important to preserve the 1.x behavior in IDE2)
    - The error message is toasted when the IDE2 prompts with the modal dialog.
        ```
        ./Arduino\ IDE.app/Contents/MacOS/Arduino\ IDE ./1612-sketches/invalid-sketches/Bar 
        ```
       Screen Shot 2022-11-08 at 13 55 07

        ```
        ./Arduino\ IDE.app/Contents/MacOS/Arduino\ IDE ./1612-sketches/invalid-sketches/foo
        ```
       Screen Shot 2022-11-08 at 13 55 32

> * The fallback sketch editor is already opened in IDE2 when the modal dialog prompts the move (this is important to preserve the 1.x behavior in IDE2)
> * The error message is toasted when the IDE2 prompts with the modal dialog.

If one of these 👆 is not working due to a slower or different env OS, please let me know, and I will adjust the timings.

Closes #1612

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: arduino-ide-extension/src/browser/contributions/open-sketch-files.ts [hunk 1]
```diff
@@ -135,39 +130,29 @@ export class OpenSketchFiles extends SketchContribution {
...
+    if (widget && !forceOpen) {
+      return widget;
+    }
+
     const disposables = new DisposableCollection();
-    if (!widget || forceOpen) {
-      const deferred = new Deferred<EditorWidget>();
+    const deferred = new Deferred<EditorWidget>();
+    if (!widget) {
+      // If the editor or is not defined, assume one on create event
```
Comment (AlbyIanna) [inline arduino-ide-extension/src/browser/contributions/open-sketch-files.ts:140]: I don't understand this comment. @kittaakos could you please elaborate on this?

File: arduino-ide-extension/src/browser/contributions/open-sketch-files.ts [hunk 2]
```diff
@@ -176,29 +161,39 @@ export class OpenSketchFiles extends SketchContribution {
...
+      .open(
         new URI(uri),
         options ?? {
           mode: 'reveal',
           preview: false,
           counter: 0,
         }
+      )
+      .then((editorWidget) => {
+        // if the widget was already opened we assume it was already already visible and attached to the DOM
```
Comment (AlbyIanna) [inline arduino-ide-extension/src/browser/contributions/open-sketch-files.ts:176]:
```suggestion
        // if the widget was already opened we assume it was already visible and attached to the DOM
```

**Review by AlbyIanna — APPROVED** [review]
Everything works as described and I couldn't find regressions with #1563.

Code is also good for me.

File: arduino-ide-extension/src/browser/contributions/open-sketch-files.ts (hunk 1 above)
Comment (kittaakos) [reply arduino-ide-extension/src/browser/contributions/open-sketch-files.ts:140]: Thanks for asking!

We should improve it. I am open to any proposals. Your recent recommendations for clarifying code comments were on the spot 👍 

When `ensureOpened` is called, the editor can be in two different primary states:
 - It's not opened. The editor widget and the backing monaco editor instance do not exist, and the editor widget is not yet registered to the `editorManager`. The `widget` is `undefined`.
 - It's opened
    - the editor widget is the top editor. The editor has the focus (the cursor blinks in it); it's the [`activeEditor`](https://github.com/eclipse-theia/theia/blob/7abca9d57c966d621f2acc26008cf1a9e454949b/packages/editor/src/browser/editor-manager.ts#L138-L144).
    - the editor widget is the top editor, but the focus is on a different widget, or the context menu is active in the editor; it's the [`currentEditor`](https://github.com/eclipse-theia/theia/blob/7abca9d57c966d621f2acc26008cf1a9e454949b/packages/editor/src/browser/editor-manager.ts#L162-L168).
    - the editor widget is not on top. The tab with the filename is visible.

When the `widget` is `undefined`, the framework will instantiate it when calling `editorManager.open`. After the editor widget creation, `editorManager.onCreated` gets an event. IDE2 must handle this case differently, listen to this event, and ensure that the editor is attached to the shell and visible on the screen. Then resolve the promise.

If the `widget` is already defined, it's opened; hence, there is no need to wait for any visibility state changes. This case does not need to wait for any events.

Please help to improve the comment.

Comment (kittaakos) [reply arduino-ide-extension/src/browser/contributions/open-sketch-files.ts]: I have updated the comments. Please re-check them. Thank you!

**Review by per1234 — APPROVED** [review]
I verified this fixes the problem of the exceptionally long first load time for multi-file sketches reported at https://github.com/arduino/arduino-ide/issues/1612.

I also checked for regressions in handling of opening sketches with invalid format on both Windows and Linux.

Thanks Akos!
