### PR TITLE
#608, #229 Reveal the error location after the failed verify

### LINKED ISSUE #229: Display error messages from Compiler and Linker in red...
OSX 11.1
2.0.0.b3

Older IDE reported errors in red to make it easy to spot in compiler and linker output

### LINKED ISSUE #608: The user is not guided to the error line when an error is encountered after verifying/uploading the sketch
**Describe the bug**
If an error is encountered when trying to compile or upload, in code editor the user is not guided  to the line of code where the first encountered error is located. This is annoying especially when dealing with long code or multiple .ino tab, because the user is not sure on where the error is located, making it difficult to spot and troubleshoot it.

**To Reproduce**
1. Go to 'File'
2. Go to 'Examples > Strings'
3. Open 'StringReplace' sketch
4. Go to line 46
5. Delete the semicolon ";" at the end of line
6. Scroll on top of code
7. Click Verify (or Upload) button on top bar of IDE GUI

**Expected behavior**
When an error is encountered trying to compile or upload In code editor I expect to be brought with the cursor to the first error found in the workspace. 

**Screenshots**
Actual behaviour - IDE 2 beta12 

Expected (Java IDE legacy behaviour)

**Desktop (please complete the following information):**
 - OS: All
 - Version: 2.0.0 beta12

**Additional context**
This behavior was consolidated in Java IDE.

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

 - To reveal the compilation error location in the editor after a failed verify. The first compiler error is extracted from the CLI output and the IDE2 reveals it. (#608)

https://user-images.githubusercontent.com/1405703/173849256-bd6e6797-15a5-474d-b93e-6e58282c67e6.mp4

 - Show the errors with error color in the _Output_ view (https://github.com/arduino/arduino-ide/issues/229).

Screen Shot 2022-06-15 at 16 15 54

 - Show the first compilation error in the notification center.
Screen Shot 2022-06-15 at 16 17 01

 - Can copy the _Output_ content from the error notification:

https://user-images.githubusercontent.com/1405703/173850735-bb65386b-51d2-4dab-b1fd-c95d65c0b389.mp4

### Experimental
You need to enable the experimental features from the `settings.json` if you want to see "more errors" 😉:
 - Open the _Command Palette_ with <kbd>F1</kbd>,
 - Type and `Preferences: Open Settings (JSON)` and press <kbd>Enter</kbd>,
 - Add `"arduino.compile.experimental": true` to the JSON, save the file if you do not have auto-save enabled, and close the `settings.json` editor.
 - Compile a sketch with multiple errors. Here is an example sketch:
[Errors.zip](https://github.com/arduino/arduino-ide/files/8911126/Errors.zip)

It should be possible to navigate between the errors.

https://user-images.githubusercontent.com/1405703/173874548-c6a8ed04-4952-4077-b64a-67b8c0515a00.mp4

Expected behavior:
 - The order of the compiler errors is given by the CLI (https://github.com/arduino/arduino-cli/issues/1760),
 - The `Next Error` and the `Previous Error` navigation depend on the order of the compiler errors,
 - The error parsing logic in IDE2 is [expected to be identical](https://github.com/arduino/arduino-ide/pull/1064/files#diff-f189f49a2c2650a5e2c1fc3c37e3993e049c3db6a9fa7b83ecdac4a988b65026R91-R95) as in the Java IDE.
 - If the experimental features are enabled, but there is one compiler error, navigation is not available.
 - If the cursor location intersects the location of the compiler error, or in the same line, the error under the cursor will be the current error and will have the previous/next action. (~There is an issue when there are multiple errors in the same line or location. I am working on this. 🚧 https://github.com/arduino/arduino-ide/pull/1064#discussion_r898193686~ Fixed: https://github.com/arduino/arduino-ide/pull/1064/commits/4f486cb4a2c2cdfc388d167ea3c6f5b5ed684300)
 - The error decoration (red line) must be sticky. It means, that editing the file should move the markers around.
 - If a code is deleted from an error decoration location, or text is inserted into an error decoration location, the error decoration will be removed.

https://user-images.githubusercontent.com/1405703/173877180-104d6456-ce7e-4ac8-9fe4-a2227646bffd.mp4

Known issues:
 - When deleting code from a location with the error decoration.

https://user-images.githubusercontent.com/1405703/173877699-6bd92a9c-2585-4cbd-bf32-a6026f67a751.mp4
 - TBD,

Open questions:
 - As noted [in the code](https://github.com/arduino/arduino-ide/pull/1064/files#diff-5cf4185feeb098a1b6102d6443d9aa3885075289fac0d3b2bd12557897287b78R420-R422), I do not know which focusing logic prefers the community the best. So I would like to hear feedback. ~I will add a preference for this soon.~ I added a preference: https://github.com/arduino/arduino-ide/pull/1064/commits/54e60f6e111d53e969fb08bf4c30f9ae5db3cbce

### Other information

Closes #608
Closes #229

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: arduino-ide-extension/src/browser/contributions/compiler-errors.ts [hunk 1]
```diff
@@ -0,0 +1,478 @@
...
+
+  private async handleSelectionChange(
+    uri: string,
+    selection: Range
+  ): Promise<void> {
+    const monacoSelection = this.p2m.asRange(selection);
+    console.log(
+      `Handling selection change in editor ${uri}. New (monaco) selection: ${monacoSelection.toJSON()}`
+    );
+    const intersectsError = (
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/compiler-errors.ts:338]: This should favor intersection over the same line match. This is a bug.

File: arduino-ide-extension/src/browser/contributions/compiler-errors.ts [hunk 2]
```diff
@@ -0,0 +1,478 @@
...
+    };
+  }
+
+  private compilerErrorDecoration(range: Range): EditorDecoration {
+    return {
+      range,
+      options: {
+        isWholeLine: true,
+        className: 'core-error',
+        stickiness: TrackedRangeStickiness.AlwaysGrowsWhenTypingAtEdges,
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/compiler-errors.ts:304]: This might be the problem when deleting content from marked lines. Fix it!

File: arduino-ide-extension/src/common/protocol/core-service.ts [hunk 3]
```diff
@@ -9,6 +17,78 @@ export const CompilerWarningLiterals = [
...
+    Upload: 4002,
+    UploadUsingProgrammer: 4003,
+    BurnBootloader: 4004,
+  };
+  export const VerifyFailed = create(Codes.Verify);
+  export const UploadFailed = create(Codes.Upload);
+  export const UploadUsingProgrammerFailed = create(
+    Codes.UploadUsingProgrammer
+  );
+  export const BurnBootloaderFailed = create(Codes.BurnBootloader);
```
Comment (kittaakos) [inline arduino-ide-extension/src/common/protocol/core-service.ts:68]: Nice to have: burn bootloader is unrelated to the sketch content, IDE2 won't ever get a location, so consider having a different error type.

File: arduino-ide-extension/src/common/protocol/core-service.ts [hunk 4]
```diff
@@ -9,6 +17,78 @@ export const CompilerWarningLiterals = [
...
+      ApplicationError.is(error) &&
+      Object.values(Codes).includes(error.code)
+    );
+  }
+  function create(
+    code: number
+  ): ApplicationError.Constructor<number, ErrorInfo[]> {
+    return ApplicationError.declare(
+      code,
+      (message: string, data: ErrorInfo[]) => {
```
Comment (kittaakos) [inline arduino-ide-extension/src/common/protocol/core-service.ts:83]: Nice to have: consider replacing `message` with a `ServiceError` instance.

File: arduino-ide-extension/src/node/core-service-impl.ts [hunk 5]
```diff
@@ -304,9 +345,36 @@ export class CoreServiceImpl extends CoreClientAware implements CoreService {
...
+      grpcPort.setProtocolLabel(port.protocolLabel);
+    }
+    return grpcPort;
+  }
+}
+/**
+ * Artificial common interface for all gRPC streaming requests.
+ * Such as `UploadResponse,` `UploadUsingProgrammerResponse`, `BurnBootloaderResponse`, and the `CompileResponse`.
+ */
+interface StreamingResponse {
```
Comment (kittaakos) [inline arduino-ide-extension/src/node/core-service-impl.ts:363]: Why not union types?

**Review by per1234 — COMMENTED** [review]
It may be out of scope for this PR, but I think the color used for stderr in the output panel with the "Light (Arduino)" theme must be made lighter.

Here is how it looks in Arduino IDE 1.8.19:

1 8 19-stderr

Compare that to the color when using the build from this PR:

2 x-stderr

At one point, this color in Arduino IDE 1.x was changed to a similar darker red until it was restored to the current color after complaints about readability from the users:

- https://github.com/arduino/Arduino/issues/2901
- https://github.com/arduino/Arduino/issues/3056

**Review by per1234 — COMMENTED** [review]
UPDATE: resolved

<s>

More of a "nice to have" than something really essential, but I thought I would mention it since I did notice it by chance.

Would it be possible to still get selection highlighting on the text of the line with the error highlighting?

Notice how the selected text on the error line has a yellow background in Arduino IDE 1.8.19:

image

While there is no visual indication of the same selection on that line when using the build from this PR:

image

</s>

**Comment by kittaakos** [comment]
Thank you for trying it out!

> It may be out of scope for this PR, but I think the color used for stderr in the output panel with the "Light (Arduino)" theme must be made lighter.

I propose opening a follow-up for this. Currently, IDE2 uses the default [`--theia-inputValidation-errorBackground`](https://github.com/arduino/arduino-ide/pull/1064/files#diff-fd49e724c8f3bdaf5b42718fe91cfd5ad68819cf8b0ee3b2d2cbb302bde3246fR13) value. The designer team can work on it and align the default Theia "error color" to the Arduino theme.

> Would it be possible to still get selection highlighting on the text of the line with the error highlighting.

Nice catch! Sure. I look into it.

**Comment by kittaakos** [comment]
> Notice how the selected text on the error line has a yellow background in Arduino IDE 1.8.19:
> 
> image
> 
> While there is no visual indication of the same selection on that line when using the build from this PR:
> 
> image

✅ Fixed

https://user-images.githubusercontent.com/1405703/174077312-de047930-f440-4bc1-85f5-8f7ae88833a5.mp4

File: arduino-ide-extension/src/node/core-service-impl.ts (hunk 5 above)
Comment (kittaakos) [reply arduino-ide-extension/src/node/core-service-impl.ts]: https://github.com/arduino/arduino-ide/pull/1064/commits/c8e22407db5c24d8b11ee0fd16c6cf4b1b8441c2

File: arduino-ide-extension/src/common/protocol/core-service.ts [hunk 6]
```diff
@@ -9,6 +17,78 @@ export const CompilerWarningLiterals = [
...
+      const sameRange = (left: Range, right: Range) =>
+        left.start.line === right.start.line &&
+        left.start.character === right.start.character &&
+        left.end.line === right.end.line &&
+        left.end.character === right.end.character;
+      const sameLocation = (left: Location, right: Location) =>
+        left.uri === right.uri && sameRange(left.range, right.range);
+      return (
+        left.message === right.message &&
+        left.details === right.details &&
```
[the remark this answers is not in the document]
Comment (kittaakos) [reply arduino-ide-extension/src/common/protocol/core-service.ts]: https://github.com/arduino/arduino-ide/pull/1064/commits/15f1411461443fd357ede07ad0cb00a613b88b83

File: arduino-ide-extension/src/browser/contributions/compiler-errors.ts [hunk 7]
```diff
@@ -0,0 +1,478 @@
...
+    location: Location
+  ): Promise<EditorWidget | undefined> {
+    const { uri, range } = location;
+    const editor = await this.editorManager.getByUri(new URI(uri), {
+      mode: 'activate',
+    });
+    if (editor && this.shell) {
+      // to avoid flickering, reveal the range here and not with `getByUri`, because it uses `at: 'center'` for the reveal option.
+      // TODO: check the community reaction whether it is better to set the focus at the error marker. it might cause flickering even if errors are close to each other
+      editor.editor.revealRange(range, { at: 'centerIfOutsideViewport' });
```
[the remark this answers is not in the document]
Comment (kittaakos) [reply arduino-ide-extension/src/browser/contributions/compiler-errors.ts]: https://github.com/arduino/arduino-ide/pull/1064/commits/54e60f6e111d53e969fb08bf4c30f9ae5db3cbce

File: arduino-ide-extension/src/node/utils/simple-buffer.ts [hunk 8]
```diff
@@ -1,31 +1,74 @@
...
+      [OutputMessage.Severity.Info, []],
+    ]);
+  }
+  export function clear(chunks: Chunks): Chunks {
+    for (const chunk of chunks.values()) {
+      chunk.length = 0;
+    }
+    return chunks;
+  }
+  export function isEmpty(chunks: Chunks): boolean {
```
Comment (davegarthsimpson) [inline arduino-ide-extension/src/node/utils/simple-buffer.ts:56]: return [ ...map.values()].some(v => v.length) maybe more concise?

Comment (davegarthsimpson) [inline arduino-ide-extension/src/node/utils/simple-buffer.ts:56]: return ![ ...map.values()].some(v => v.length)

File: arduino-ide-extension/src/browser/contributions/compiler-errors.ts [hunk 9]
```diff
@@ -0,0 +1,478 @@
...
+  private async handleCompilerErrorsDidChange(
+    errors: CoreError.Compiler[]
+  ): Promise<void> {
+    this.toDisposeOnCompilerErrorDidChange.dispose();
+    const compilerErrorsPerResource = this.groupByResource(
+      await this.filter(errors)
+    );
+    const decorations = await this.decorateEditors(compilerErrorsPerResource);
+    this.errors.push(...decorations.errors);
+    this.toDisposeOnCompilerErrorDidChange.pushAll([
```
[the remark this answers is not in the document]
Comment (kittaakos) [reply arduino-ide-extension/src/browser/contributions/compiler-errors.ts:245]: https://github.com/arduino/arduino-ide/pull/1064/commits/3ae1063415f4027061d876d380eee0d57afccf4b

File: arduino-ide-extension/src/node/utils/simple-buffer.ts (hunk 8 above)
Comment (kittaakos) [reply arduino-ide-extension/src/node/utils/simple-buffer.ts:56]: https://github.com/arduino/arduino-ide/pull/1064/commits/982f399414ae25b8dca72d6b100b8cca9ebd8f30

File: arduino-ide-extension/src/node/core-service-impl.ts [hunk 10]
```diff
@@ -19,282 +23,323 @@ import {
...
+  }
+
+  private async notifyUploadWillStart({
+    board,
+    port,
+  }: {
+    board?: Board | undefined;
+    port?: Port | undefined;
+  }): Promise<void> {
+    this.monitorManager.notifyUploadStarted(board, port);
```
[the remark this answers is not in the document]
Comment (kittaakos) [reply arduino-ide-extension/src/node/core-service-impl.ts]: https://github.com/arduino/arduino-ide/pull/1064/commits/aad03a2eb740ba6f15aa14586ced2eb676f96a6b

Thank you! I added the missing `return`.

> these monitorManager "notify functions" 

Why these? I understand that the upload should `await` for the monitor to pause, but why does the upload have to `await` after the upload?

File: arduino-ide-extension/src/common/protocol/core-service.ts (hunk 4 above)
Comment (kittaakos) [reply arduino-ide-extension/src/common/protocol/core-service.ts:54]: The `ServiceError` object does not contain sufficient info about the error, so this won't fix.

Ref: https://github.com/arduino/arduino-cli/issues/1767

File: arduino-ide-extension/src/node/core-service-impl.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (davegarthsimpson) [reply arduino-ide-extension/src/node/core-service-impl.ts]: sorry with "these" I was only referring to the first point about misleading naming, regarding awaiting the "notify...Finished". Correct, following through the call stack I can't see why we'd care so much about waiting for the relevant monitor service/s to restart after upload, in fact it's probably outright wrong to wait as doing so we're probably delaying return of `uploadSketch` unnecessarily

File: arduino-ide-extension/src/browser/contributions/compiler-errors.ts (hunk 2 above)
Comment (kittaakos) [reply arduino-ide-extension/src/browser/contributions/compiler-errors.ts:380]: Fixed. Custom `TextDocumentChangeEvent` tracing has been added.

**Comment by kittaakos** [comment]
I fixed all outstanding issues and made the PR ready for review. Please verify. Thank you!

File: arduino-ide-extension/src/node/core-service-impl.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (davegarthsimpson) [reply arduino-ide-extension/src/node/core-service-impl.ts]: yup

[the remark this answers is not in the document]
Comment (davegarthsimpson) [reply arduino-ide-extension/src/node/core-service-impl.ts]: + blocking the upload in this context also makes sense, because allowing it while we're potentially "reconciling" services may break things

**Review by per1234 — APPROVED** [review]
It is working great for me.

Thanks for this very valuable advancement Akos!

**Comment by kittaakos** [comment]
@davegarthsimpson please review e7ee86197dc0d06758990e52798ff087aac7fdf2 for #1074. I verified it locally, but I would appreciate a double-check. Thank you!
