### PR TITLE
fix: jsonc parsing in the IDE2 backend

### LINKED ISSUE #1945: settings.json parsing fails on the IDE2 backend if settings.json has comments
### Describe the problem

VS Code, Theia, and IDE2 use a relaxed version of JSON for storing the settings in the `settings.json` file: https://code.visualstudio.com/Docs/languages/json#_json-with-comments

If I have the following `settings.json` content, it is entirely valid but does not work on the IDE2's backend:

JSONC:
```jsonc
{
  // "arduino.cli.daemon.debug": false
  // it's a valid jsonc
}
```

VS.
 
JSON:

```json
{
  // "arduino.cli.daemon.debug": false
  // it's an invalid json
}
```

### To reproduce

There are multiple silent problems, but here is a user-facing bug:

 - Enable `arduino.sketch.inoBlueprint` and verify that it works:| when you create a new sketch, your preferred default `.ino` content is used for the new sketch.
 - Open the `settings.json` and command out any other preference with `//`.
 - Restart IDE2 and create a new sketch. IDE2 creates the new sketch with the default content, not the user-defined one.

### Expected behavior

 - IDE2 backend can handle JSONC in settings.json, not only JSON.
- The suboptimal setting parsing on the IDE2 backend is single-sourced.

### Arduino IDE version

2.0.4

### Operating system

macOS

### Operating system version

12.6.3

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

Relaxed the `settings.json` parsing in the IDE2's backend. The problem occurred when the `settings.json` contained comments or a trailing comma.

### Change description

Use `jsonc-parser` and allow comments, a trailing comma, and empty content.

### Reviewer checklist

Closes #1945

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: arduino-ide-extension/src/node/arduino-daemon-impl.ts [hunk 1]
```diff
@@ -149,34 +151,12 @@ export class ArduinoDaemonImpl
...
-  // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  private tryParse(raw: string): any | undefined {
-    try {
-      return JSON.parse(raw);
-    } catch {
-      return undefined;
+    const settings = await this.settingsReader.read();
+    if (settings) {
+      const value = settings['arduino.cli.daemon.debug'];
+      return typeof value === 'boolean' && !!value;
```
Comment (AlbyIanna) [inline arduino-ide-extension/src/node/arduino-daemon-impl.ts:157]: The strict equality operator (`===`) returns `false` if the types of the two operands are different.

```suggestion
      return value === true
```

**Review by AlbyIanna — APPROVED** [review]
code LGTM 👍

**Review by per1234 — APPROVED** [review]
