### PR TITLE
Fix boards listing

### LINKED ISSUE #802: Sort Board menus like the classic IDE does
## Describe the current behavior

Arduino IDE 1.x sorts the menu for each platform in **Tools > Board** (e.g., **Tools > Board > Arduino AVR Boards**) according to the order of occurrence of the `name` property for each board definitions in the platform's [`boards.txt` configuration file](https://arduino.github.io/arduino-cli/dev/platform-specification/#boardstxt). This allows the platform developer to sort the boards in some logical order in the menu (e.g., putting commonly used boards at the top of the menu, or grouping related boards together).

Arduino IDE 2.x sorts them by alphabetical order, which gives the platform author no control. For example, in the Arduino IDE 2.x menu for the **Arduino AVR Boards** platform menu, the first 8 boards are 3rd party or retired.

Arduino IDE 1.x:

image

Arduino IDE 2.x:

image

## To reproduce

1. Select **Tools > Board > Arduino AVR Boards** from the Arduino IDE menus.
1. Note the order of the boards in the menu.
1. Compare this to the order of occurrence of the `name` properties for each board definition in the platform's `boards.txt` file:
   https://github.com/arduino/ArduinoCore-avr/blob/1.8.4/boards.txt

🙁 the Arduino IDE menu sort order does not match the order in `boards.txt`

## Describe the request

**Tools > Board** menu for each platform is sorted according to the order in `boards.txt`.

## Desktop

- OS: Windows 10
- Version: 2.0.0-rc3-snapshot.759b410
Date: 2022-01-31T13:15:29.574Z
CLI Version: 0.20.2 [13783819]

### Related:

- https://github.com/arduino/arduino-ide/pull/486
- https://github.com/arduino/arduino-ide/issues/801

### PR DESCRIPTION
**Pull request by AlbyIanna**
### Motivation
The IDE needs to sort the menu for each platform in **Tools > Board** (e.g., **Tools > Board > Arduino AVR Boards**) according to the order of occurrence of the `name` property for each board definitions in the platform's [`boards.txt` configuration file](https://arduino.github.io/arduino-cli/dev/platform-specification/#boardstxt).

### Change description
- use `listall` instead of `search` command in the arduino-cli
- add a proper order to the menu item when registering a board
- update the arduino-cli to use the sorting fix

### Other information
Fixes #802.

This needed a fix in the CLI to get the correct order: https://github.com/arduino/arduino-cli/pull/1903

This PR is in **draft** because there isn't a release for the arduino-cli yet, but it can already be tested.

**Arduino IDE 2.x** _before_ this change:
image

**Arduino IDE 2.x** _after_ this change:
Screenshot 2022-10-04 at 10 51 36

**Arduino IDE 1.x**:
Screenshot 2022-10-04 at 10 51 46

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by kittaakos — CHANGES_REQUESTED** [review]
This won't work. If IDE2 uses `board list` instead of `board search`, then only boards from installed platforms will be searched.

Steps to reproduce:
 - Delete ⚠️ (or rename) the `directories/data` location,
 - Start IDE2 from this PR,
 - Use the board search.


https://user-images.githubusercontent.com/1405703/193806370-e885ff3a-c429-4076-a9e7-c530c351203c.mp4

**Comment by AlbyIanna** [comment]
> This won't work. If IDE2 uses board list instead of board search, then only boards from installed platforms will be searched.

Right. I've fixed it by adding a separate method to get only the installed boards.

**Review by kittaakos — CHANGES_REQUESTED** [review]
Please reuse the code instead of copy/pasting it.

https://github.com/arduino/arduino-ide/pull/1520/files#diff-c0fc7c4dd9afbf95ea0168ace3b7e01e84078a50ba6cd54896f8a095f83f30ffL202-R225

**Comment by AlbyIanna** [comment]
> Please reuse the code instead of copy/pasting it.

Done

**Comment by kittaakos** [comment]
> Done

Thank you! I will do the verification soon. Which issue does this PR suppose to close? I could not find it in the commits or PR description. The closest was #801.

**Comment by AlbyIanna** [comment]
> The closest was https://github.com/arduino/arduino-ide/issues/801.

Pretty close, it fixes #802. Added to the PR's description.

**Review by per1234 — CHANGES_REQUESTED** [review]
The order of the boards is not correct for me:

image

### Arduino IDE version

2.0.1-snapshot-3f7230e (tester build for https://github.com/arduino/arduino-ide/pull/1520/commits/56f2ac3b5b3218cd2088682793f738670456370e)

### Operating system

Windows 10, Ubuntu 20.04

### Additional context

The order is as expected when using Arduino CLI:

```text
$ arduino-cli version
arduino-cli.exe  Version: git-snapshot Commit: 3d5a87e1 Date: 2022-10-04T18:01:41Z

$ arduino-cli board listall arduino:avr --format json | jq '.boards[] | .name'
"Arduino Yún"
"Arduino Uno"
"Arduino Uno Mini"
"Arduino Duemilanove or Diecimila"
"Arduino Nano"
"Arduino Mega or Mega 2560"
"Arduino Mega ADK"
"Arduino Leonardo"
"Arduino Leonardo ETH"
"Arduino Micro"
"Arduino Esplora"
"Arduino Mini"
"Arduino Ethernet"
"Arduino Fio"
"Arduino BT"
"LilyPad Arduino USB"
"LilyPad Arduino"
"Arduino Pro or Pro Mini"
"Arduino NG or older"
"Arduino Robot Control"
"Arduino Robot Motor"
"Arduino Gemma"
"Adafruit Circuit Playground"
"Arduino Yún Mini"
"Arduino Industrial 101"
"Linino One"
"Arduino Uno WiFi"
```

File: arduino-ide-extension/src/node/boards-service-impl.ts [hunk 1]
```diff
@@ -199,8 +201,28 @@ export class BoardsServiceImpl
...
+  }
+
+  async getInstalledBoards(): Promise<BoardWithPackage[]> {
+    const { instance, client } = await this.coreClient;
+    const req = new BoardListAllRequest();
+    req.setInstance(instance);
+    return this.handleListBoards(client.boardListAll.bind(client), req);
+  }
+
+  async handleListBoards(
```
Comment (kittaakos) [inline arduino-ide-extension/src/node/boards-service-impl.ts:214]: The visibility should be `private` if it's not called from outside of the module.

**Review by kittaakos — CHANGES_REQUESTED** [review]
I have noticed that sometimes the order of installed boards does not match with IDE 1.x Sometimes it's correct.

IDE2 SAMD:
Screen Shot 2022-10-05 at 16 47 00

IDE 1.x SAMD:
Screen Shot 2022-10-05 at 16 45 50

IDE2 AVR:
Screen Shot 2022-10-05 at 16 47 10

IDE 1.x AVR:
Screen Shot 2022-10-05 at 16 47 24

File: arduino-ide-extension/src/browser/contributions/board-selection.ts [hunk 2]
```diff
@@ -239,14 +240,18 @@ PID: ${PID}`;
       };
 
       // Board menu
-      const menuAction = { commandId: id, label: name };
+      const menuAction = {
+        commandId: id,
+        label: name,
+        order: `${index}`,
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/board-selection.ts:246]: We can check them together, but I think this is the classic alphabetic ordering issue. 

```sh
% node    
Welcome to Node.js v14.19.0.
Type ".help" for more information.
> ['1', '2', '3', '11', '12', '111'].sort()
[ '1', '11', '111', '12', '2', '3' ]
> .exit
```

With some zero padding, it works for me locally:

```diff
diff --git a/arduino-ide-extension/src/browser/contributions/board-selection.ts b/arduino-ide-extension/src/browser/contributions/board-selection.ts
index 2241c925..466e4f63 100644
--- a/arduino-ide-extension/src/browser/contributions/board-selection.ts
+++ b/arduino-ide-extension/src/browser/contributions/board-selection.ts
@@ -243,7 +243,7 @@ PID: ${PID}`;
       const menuAction = {
         commandId: id,
         label: name,
-        order: `${index}`,
+        order: String(index).padStart(4), // pads with leading zeros for alphanumeric sort where order is 1, 2, 11, and NOT 1, 11, 2
       };
       this.commandRegistry.registerCommand(command, handler);
       this.toDisposeBeforeMenuRebuild.push(
```

----

Great that your changes revealed the flaw in the codebase. These are probably all incorrect:

https://github.com/arduino/arduino-ide/blob/61a11a0857dd03c6057a558604fba810ac5955c0/arduino-ide-extension/src/browser/boards/boards-data-menu-updater.ts#L114

https://github.com/arduino/arduino-ide/blob/61a11a0857dd03c6057a558604fba810ac5955c0/arduino-ide-extension/src/browser/contributions/sketch-control.ts#L179

👇 This probably works only because the _open recent_ is limited to ten items.
https://github.com/arduino/arduino-ide/blob/61a11a0857dd03c6057a558604fba810ac5955c0/arduino-ide-extension/src/browser/contributions/open-recent-sketch.ts#L96

Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/contributions/board-selection.ts:246]: Nice one! Thank you for the suggestion!

Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/contributions/board-selection.ts:246]: I've pushed the suggestion, could you please verify it now?

**Comment by kittaakos** [comment]
@AlbyIanna, I have restarted the failed job. If you mark the PR ready, I will do the final verification. The code looks great. Thanks!

**Review by per1234 — APPROVED** [review]
It is working perfectly for me now.

Thanks Alberto!

**Review by kittaakos — APPROVED** [review]
