### PR TITLE
Move primary buttons on the right of the dialogs

### LINKED ISSUE #1368: Align the primary button in all dialogs in IDE2
### Describe the problem

Sometimes, the primary buttons (dark green color with the Light Arduino theme) are on the left, sometimes they're on the right. Align them.

### To reproduce

Screen Shot 2022-08-30 at 10 38 08
Screen Shot 2022-08-30 at 10 37 23
Screen Shot 2022-08-30 at 10 37 17
Screen Shot 2022-08-30 at 10 37 08

image (1)

### Expected behavior

The primary buttons are on the right.

### Arduino IDE version

34a7fdb

### Operating system

macOS

### Operating system version

12.5.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by francescospissu**
### Motivation
In some dialogs, the primary button is not on the right.

### Change description
Move all primary buttons in dialogs to the right.

Screenshot 2022-09-01 142402

Screenshot 2022-09-01 142929

Screenshot 2022-09-02 114253

### Other information
Closes #1368.

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: arduino-ide-extension/src/browser/library/library-list-widget.ts [hunk 1]
```diff
@@ -201,7 +201,8 @@ class MessageBoxDialog extends AbstractDialog<MessageBoxDialog.Result> {
       options.buttons || [nls.localize('vscode/issueMainService/ok', 'OK')]
     ).forEach((text, index) => {
       const button = this.createButton(text);
-      button.classList.add(index === 0 ? 'main' : 'secondary');
+      const i = options.buttons ? options.buttons?.length - 1 : 0;
+      button.classList.add(index === i ? 'main' : 'secondary');
```
Comment (AlbyIanna) [inline arduino-ide-extension/src/browser/library/library-list-widget.ts:205]: This code works fine, but for readability reasons I would prefer to see something like this:
```suggestion
      const isPrimaryButton = index === options.buttons?.length - 1 : 0;
      button.classList.add(isPrimaryButton ? 'main' : 'secondary');
```
What do you think? @francescospissu

File: arduino-ide-extension/src/browser/theia/workspace/workspace-input-dialog.ts [hunk 2]
```diff
@@ -14,12 +14,17 @@ export class WorkspaceInputDialog extends TheiaWorkspaceInputDialog {
...
-    this.appendCloseButton(
-      nls.localize('vscode/issueMainService/cancel', 'Cancel')
-    );
+    if (this.acceptButton) {
+      this.controlPanel.removeChild(this.acceptButton);
+      this.appendCloseButton(
+        nls.localize('vscode/issueMainService/cancel', 'Cancel')
+      );
+      this.appendAcceptButton();
+    }
```
Comment (AlbyIanna) [inline arduino-ide-extension/src/browser/theia/workspace/workspace-input-dialog.ts:27]: It feels weird to me to add the accept button first, then remove it and then add it again only to add the close button before it.

I would prefer to override `this.appendCloseButton` with something like this:
```
  private override appendCloseButton(text: string): HTMLButtonElement {
    this.closeButton = this.createButton(text);
    this.controlPanel.insertBefore(this.closeButton, this.acceptButton);
    this.closeButton.classList.add('secondary');
    return this.closeButton;
  }
```
This should work correctly if you change back the constructor code to the previous state
```
this.appendCloseButton(
      nls.localize('vscode/issueMainService/cancel', 'Cancel')
    );
```

File: arduino-ide-extension/src/browser/library/library-list-widget.ts (hunk 1 above)
Comment (francescospissu) [reply arduino-ide-extension/src/browser/library/library-list-widget.ts:205]: I think a piece of code is missing in your suggestion because in this way it couldn't work.

Do you mean something like this?

```javascript
const isPrimaryButton = index === (options.buttons ? options.buttons?.length - 1 : 0);
button.classList.add(isPrimaryButton ? 'main' : 'secondary');
```

Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/library/library-list-widget.ts:205]: You're right, I made a mistake. This is what I wanted to suggest actually:
```
const isPrimaryButton = index === options.buttons?.length - 1;
button.classList.add(isPrimaryButton ? 'main' : 'secondary');
```
This should work the same – although I haven't tried it – and for me it's easier to read.
But your latest suggestion works as well for me, whatever you prefer.

Comment (francescospissu) [reply arduino-ide-extension/src/browser/library/library-list-widget.ts]: I've tried it before but haven't used it because but this error is thrown:

```
Object is possibly 'undefined'.
```

I've added the other change [here](https://github.com/arduino/arduino-ide/pull/1382/commits/eb37f689cce9db34f60297962c58f8ec218d98f3).

File: arduino-ide-extension/src/browser/theia/workspace/workspace-input-dialog.ts (hunk 2 above)
Comment (francescospissu) [reply arduino-ide-extension/src/browser/theia/workspace/workspace-input-dialog.ts]: I tried to do this using both `insertBefore` and `prepend` but failed.

The solution you are proposing is not working as it is, I did another change [here](https://github.com/arduino/arduino-ide/pull/1382/commits/c7cdaa6ef0585ec33f1ba22a4e83f4cad8fe7525). Let me know if it could be better.

Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/theia/workspace/workspace-input-dialog.ts]: Looks just fine to me, thanks Franceso!

**Review by AlbyIanna — APPROVED** [review]
LGTM!

**Review by kittaakos — CHANGES_REQUESTED** [review]
I can confirm the buttons are in the correct position. I have checked:
 - new sketch file,
 - 3rd party URLs, and 
 - install lib with dependencies.


I found a problem:

https://user-images.githubusercontent.com/1405703/190369216-5e4d6c53-ff25-4efe-9678-521e83deaf00.mp4

File: arduino-ide-extension/src/browser/library/library-list-widget.ts [hunk 3]
```diff
@@ -201,7 +201,9 @@ class MessageBoxDialog extends AbstractDialog<MessageBoxDialog.Result> {
       options.buttons || [nls.localize('vscode/issueMainService/ok', 'OK')]
     ).forEach((text, index) => {
       const button = this.createButton(text);
-      button.classList.add(index === 0 ? 'main' : 'secondary');
+      const isPrimaryButton =
+        index === (options.buttons ? options.buttons?.length - 1 : 0);
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/library/library-list-widget.ts:205]: `options.buttons?.length` should be `options.buttons.length`

File: arduino-ide-extension/src/browser/style/settings-dialog.css [hunk 4]
```diff
@@ -93,4 +93,5 @@
 
 .p-Widget.dialogOverlay .dialogBlock .dialogContent.additional-urls-dialog {
     display: block;
+    overflow: hidden;
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/style/settings-dialog.css:96]: How is this change related to the primary button position?

Comment (francescospissu) [reply arduino-ide-extension/src/browser/style/settings-dialog.css:96]: It's not related to the primary button position, working on this fix I noticed that there was an overflow problem above the buttons in the "Additional Boards Manager URLs" dialog:

image

Now it appears like this:

image

File: arduino-ide-extension/src/browser/library/library-list-widget.ts (hunk 3 above)
Comment (francescospissu) [reply arduino-ide-extension/src/browser/library/library-list-widget.ts]: You're right. Changed [here](https://github.com/arduino/arduino-ide/pull/1382/commits/769f08c359f3aa02e2555d6d5e8589168abf7f97).

File: arduino-ide-extension/src/browser/style/settings-dialog.css (hunk 4 above)
Comment (kittaakos) [reply arduino-ide-extension/src/browser/style/settings-dialog.css:96]: Great. Thanks for the fix 💪

**Comment by francescospissu** [comment]
Thanks for the feedback @kittaakos, I moved the close button before the last child (primary button), now it appears like this:

image

This was the older behavior:

image

**Review by kittaakos — APPROVED** [review]
Verified. Thank you!


https://user-images.githubusercontent.com/1405703/191066479-5dfb1d11-147e-4c08-a57c-88e6085bc7b8.mp4
