### PR TITLE
#740, #1331 Use port properties

### LINKED ISSUE #740: espota.py: error: option -p: invalid integer value: '{upload.port.properties.port}'
network upload with esp8266 and esp32 core doesn't have `upload.port.properties.port` property evaluated from network port discovery

IDE 2
```
.arduino15/packages/esp8266/tools/python3/3.7.2-post1/python3" -I "/home/duro/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/espota.py" -i "192.168.1.113" -p "{upload.port.properties.port}" "--auth=a" -f "/tmp/arduino-sketch-41571935C07681B86282A62DC15FAFF8/Blink.ino.bin"
Usage: espota.py [options]

espota.py: error: option -p: invalid integer value: '{upload.port.properties.port}'
Upload error: Failed uploading: uploading error: exit status 2
```
IDE 1
>.arduino15/packages/esp8266/tools/python3/3.7.2-post1/python3 -I /home/duro/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/espota.py -i 192.168.1.113 -p 8266 --auth= -f /tmp/arduino_build_169908/Blink.ino.bin

### LINKED ISSUE #1331: Only the IP address is shown for unrecognized network boards
### Describe the problem

This is the follow-up of #1327.

Arduino IDE 2.x shows only the IP address of connected but unrecognized boards. Before #1327, `network` boards not recognized by the Arduino CLI were not listed in the "Board Selector" menu. See the changes [here](https://github.com/arduino/arduino-ide/commit/74bfdc4c56d7a1577a4e800a378c21b82c1da5f8#diff-fb37f20bea00881acee3aafddb1ecefcecf41ce59845ca1510da79e918ee0837R332-R342) and [here](https://github.com/arduino/arduino-ide/commit/74bfdc4c56d7a1577a4e800a378c21b82c1da5f8#diff-e42c82bb67e277cfa4598239952afd65db44dba55dc7d68df619dfccfa648279R409-R423).

#1327 will remove the above-mentioned filtering, and the Arduino IDE will show all `network` boards. Unfortunately, the IDE receives insufficient information from the CLI, so the IDE has no chance to show anything else but the IP.

Screen Shot 2022-08-17 at 14 41 58

Screen Shot 2022-08-17 at 14 41 40

Screen Shot 2022-08-17 at 14 41 23

The `mdns-discovery` is aware of these additional things; hence the Arduino IDE 1.x can enhance the label of an unrecognized `network` board:

```
HELLO "ciao" 1
{
  "eventType": "hello",
  "message": "Invalid HELLO command",
  "error": true
}
HELLO 1 "ciao"
{
  "eventType": "hello",
  "message": "OK",
  "protocolVersion": 1
}
START_SYNC
{
  "eventType": "start_sync",
  "message": "OK"
}
{
  "eventType": "add",
  "port": {
    "address": "10.0.1.25",
    "label": "esp32s2 at 10.0.1.25",
    "protocol": "network",
    "protocolLabel": "Network Port",
    "properties": {
      ".": "esp32s2usb",
      "auth_upload": "yes",
      "board": "esp32s2usb",
      "hostname": "esp32s2.local.",
      "port": "3232",
      "ssh_upload": "no",
      "tcp_check": "no"
    }
  }
}
```

The same information is missing from the Arduino CLI board watch (`board list -w --format json`):
```
{
  "type": "add",
  "address": "/dev/cu.usbmodem03",
  "protocol": "serial",
  "protocol_label": "Serial Port (USB)"
}
{
  "type": "add",
  "address": "10.0.1.25",
  "protocol": "network",
  "protocol_label": "Network Port"
}
```

So the IDE fails to show `esp32s2 at 10.0.1.25` and falls back to `Unknown 10.0.1.25`.

### To reproduce

The simplest way is to try it with Arduino CLI:
```
./arduino-cli board list -w --format json
```

### Expected behavior

Arduino IDE should receive the properties from the CLI discovered by the `mdns-discovery`.

```json
{
    "properties": {
      ".": "esp32s2usb",
      "auth_upload": "yes",
      "board": "esp32s2usb",
      "hostname": "esp32s2.local.",
      "port": "3232",
      "ssh_upload": "no",
      "tcp_check": "no"
    }
}
```

Or the IDE should receive the  `"label": "esp32s2 at 10.0.1.25",` from the CLI.

### Arduino IDE version

9e2b73a

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

Related (if not the same): https://github.com/arduino/arduino-ide/issues/567

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by kittaakos**
### Motivation

To show the `hostname` of the `network` port in the boards dropdown and `Tools` > `Ports` menu (#1331)
To fix the upload caused by missing port `properties` (#740) 

### Change description

 - Removed unnecessary `id` from the `Port` type. It can be derived from the `address` and `protocol`.
 - Introduced a shared `Unknown` i18n string.
 - Removed the deprecated `getAttacheBoards`/`getAvailablePorts` service APIs.
 - Use the `addressLabel` instead of the `address` in the boards dropdown and `Tools` > `Ports` menu. (#1331)
 - Introduced an optional `properties` on the `Port` type. (#740)
 - Use the `Port#properties` for the upload. (#740)
 - Better type guard for the `Port` type.
 - Refactored the board discovery and added better typing for the gRPC `DetectedPort`.

### Other information

Closes #1331
Closes #740

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
If possible, please break the changes into two PRs:

- Fix https://github.com/arduino/arduino-ide/issues/740
- Add label to network ports

My impression is that the first is an essential fix for a problem specific to the Arduino IDE 2.x code base (since the bug does not occur when uploading to these boards via Arduino CLI).

My impression is that the second is a purely cosmetic improvement that is being done in a hacky way with the intention of eventually being removed.

Since the two are so distinct, I would prefer to test and evaluate each separately.

File: arduino-ide-extension/src/node/board-discovery.ts [hunk 1]
```diff
@@ -334,21 +242,130 @@ export class BoardDiscovery
...
+
+interface DetectedPort {
+  port: Port | undefined;
+  boards: Board[];
+}
+namespace DetectedPort {
+  export function isUnrecognizedNetwork(
+    arg: DetectedPort
+  ): arg is DetectedPort & { port: Port & { protocol: 'network' } } {
+    return !!arg.port && arg.port.protocol === 'network' && !arg.boards.length;
```
Comment (per1234) [inline arduino-ide-extension/src/node/board-discovery.ts:369]: I wasn't able to understand the purpose of this newly added protocol-specific code. Would you mind providing a quick summary of why it was added @kittaakos?

Comment (kittaakos) [reply arduino-ide-extension/src/node/board-discovery.ts:369]: It's a hack and will be removed. I have not yet pushed the changes to the remote.

**Review by per1234 — CHANGES_REQUESTED** [review]
Unfortunately, this does not fix #740 for me:

Using 2.0.0-rc9.2.snapshot-7908674 (tester build for https://github.com/arduino/arduino-ide/pull/1335/commits/6cae53bfd17503aee1931e9d41014bc1de0261ea) to upload to a network port of an ESP8266 board fails with the same error:

```text
"C:\Users\per\AppData\Local\Arduino15\packages\esp8266\tools\python3\3.7.2-post1/python3" -I "C:\Users\per\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2/tools/espota.py" -i "192.168.254.130" -p "{upload.port.properties.port}" "--auth=adsg" -f "C:\Users\per\AppData\Local\Temp\arduino-sketch-C6FD83427A9EBA5E20435BABAB642981/esp8266.ino.bin"
Usage: espota.py [options]

espota.py: error: option -p: invalid integer value: '{upload.port.properties.port}'
Failed uploading: uploading error: exit status 2
```

**Comment by per1234** [comment]
>this does not fix #740 for me

After further investigation, I found that #740 now only occurs when uploading a sketch that was associated with the port while using a previous version of the Arduino IDE.

### To reproduce

1. Start any build of the Arduino IDE that doesn't have the fix made in this PR (e.g., 2.0.0-rc9.2.snapshot-ca47e8a).
1. Set up your ESP8266 board to produce a network port as usual: https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#application-example
1. Create a sketch named "**SomeSketch**".
1. Select your ESP8266 board from the **Tools > Board** menu in the Arduino IDE.
1. Select the network port of your ESP8266 board from the **Tools > Port** menu in the Arduino IDE.
1. Select **Sketch > Upload** from the Arduino IDE menus.
1. Wait for the upload to fail as expected due to #740
1. Select **File > Quit** from the Arduino IDE menus.
1. Open the "**SomeSketch**" sketch in the Arduino IDE.
   The board and port should already be selected since they have been associated with the sketch.
1. Select **Sketch > Upload** from the Arduino IDE menus.
   🐛 The upload fails unexpectedly with the same error as reported in #740
1. Select any other port from the **Tools > Port** menu in the Arduino IDE.
1. Select the network port of your ESP8266 board from the **Tools > Port** menu in the Arduino IDE.
1. Select **Sketch > Upload** from the Arduino IDE menus.
   🙂 The upload is successful.

### Additional context

Instead of the port selection flip flop described in steps 11-12 above, I was also able to resolve the issue by deleting the "User Data Folder" and restarting the IDE:

#### Windows

```text
%APPDATA%\arduino-ide\
```

(e.g., `C:\Users\<user name>\AppData\Roaming\arduino-ide\`)

#### Linux

```text
~/.config/arduino-ide/
```

#### macOS

```text
~/Library/Application Support/arduino-ide/
```

**Review by per1234 — CHANGES_REQUESTED** [review]
### Describe the problem

The [`cc.arduino.cli.commands.v1.Port` message of the Arduino CLI gRPC interface](https://arduino.github.io/arduino-cli/dev/rpc/commands/#cc.arduino.cli.commands.v1.Port) contains two fields used for primary identifiers of a port:

- `address` - identifier for machines
- `label` - identifier for humans

🐛 Unlike the "**Board Selector**" menu and "**Select Other Board and Port**" dialog, which use the human identifier `label` field value, the `address` field value is used in the **Tools > Port** menu.

### To reproduce

1. Create a port that has a `label` field value different from the `address` field value.
   I believe the two are always the same for serial ports, so this will be most easily accomplished with a network port, where the `address` value will be an IP address alone like "`192.168.254.127`", while the `label` value will typically have a form like "`esp32-b4e62dbf693d at 192.168.254.127`".
1. Open the "**Board Selector**" menu.
   🙂 The `label` field value is used.
   image
1. Select "**Select other board and port...**" from the "**Board Selector**" menu.
   🙂 The `label` field value is used in the "**PORTS**" menu.
   image
1. Open the **Tools > Port** menu.

🐛 The `address` field value is used in the **Tools > Port** menu.

image

### Expected behavior

The `label` field value is used in the **Tools > Port** menu.

### Arduino IDE version

2.0.0-rc9.2.snapshot-7908674 (tester build for 6cae53b)

### Operating system

Windows, Linux

### Operating system version

Windows 10, Linux 20.04

### Additional context

Arduino IDE 1.x uses the `label` field value in the **Tools > Port** menu:

image

---

The **Tools > Port** menu is explicitly mentioned in the original issue https://github.com/arduino/arduino-ide/issues/567, indicating to me that the expectation was for the `label` field value to be used in that menu.

---

Even though the pluggable discovery system does provide a very nice [board identification capability](https://arduino.github.io/arduino-cli/dev/pluggable-discovery-specification/#board-identification), I am not aware of any boards platforms that are actually using this capability currently. This means that these network ports will not have the "**(\<board name\>)**" suffix added to identified ports in the **Tools > Port** menu, making the prefix provided by the `label` field value especially important.

**Comment by kittaakos** [comment]
> After further investigation, I found that #740 now only occurs when uploading a sketch that was associated with the port while using a previous version of the Arduino IDE.

> 🐛 The `address` field value is used in the **Tools > Port** menu.

Both issues should be fixed now. Please check again. Thank you!

**Review by per1234 — APPROVED** [review]
I verified this fixes https://github.com/arduino/arduino-ide/issues/567, https://github.com/arduino/arduino-ide/issues/1331, and https://github.com/arduino/arduino-ide/issues/740 (including under the specific case I reported in my previous review: https://github.com/arduino/arduino-ide/pull/1335#pullrequestreview-1082348452).

Thanks for your excellent work on this Akos!
