### PR TITLE
Show user fields dialog again if upload fails

### LINKED ISSUE #1386: Show "Configure And Upload" dialog again on next attempt after failed upload
### Describe the request

Consider whether it will be an improved UX to trigger the "**Configure And Upload**" dialog again on the upload attempt following a failed upload.

This will provide a better user experience in the event the upload failed due to incorrect values entered in the dialog, but also be inconvenient in the case where the upload failed for an unrelated reason, so there is a tradeoff.

🙂 The user may find this to be a more intuitive user experience.

### Describe the current behavior

It may sometimes be necessary to integrate user provided information (e.g., a password) into the command used to upload a sketch to an Arduino board.

This capability is provided by the ["user provided fields"](https://arduino.github.io/arduino-cli/dev/platform-specification/#user-provided-fields) system.

On the first upload of a given a given sketch to a given board on a given port that is configured to use user provided fields, the Arduino IDE presents a "**Configure And Upload**" dialog (https://github.com/arduino/arduino-ide/pull/550):

image

For the convenience of the user, this information is then stored temporarily for that sketch, board, and port selection and the dialog will not be presented again unless one of the following occurs:

- A different sketch is opened
- A new board is selected
- A new port is selected
- The **Sketch > Configure and Upload** menu item is used

🙁 If the user made a mistake while filling in the dialog, or made a change that requires updating the fields, it might not be clear to them how to do that.

### Arduino IDE version

2.0.0-rc9.2.snapshot-20cc34c

### Operating system

All

### Operating system version

Any

### Additional context

Related: https://github.com/arduino/arduino-ide/issues/1359

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by AlbyIanna**
### Motivation
When uploading a sketch with user fields, if the user made a mistake while filling in the dialog, or made a change that requires updating the fields, it might not be clear to them how to do that 🙁

### Change description
As requested in #1386, I've made a change to show again the user field dialog when pressing the Upload button if the previous upload failed.

### Other information
Closes #1386 

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by kittaakos** [comment]
Is there a chance to move the entire user-fields logic to another module and let `upload-sketch` do the uploading only? Of course, this new thing should communicate with the upload contribution before upload. All user-field dialogs, prompts, etc. could go into their own service, class, or contribution. What do you think?

**Comment by AlbyIanna** [comment]
> Is there a chance to move the entire user-fields logic to another module and let `upload-sketch` do the uploading only? Of course, this new thing should communicate with the upload contribution before upload. All user-field dialogs, prompts, etc. could go into their own service, class, or contribution. What do you think?

Yes, it would make sense. I'll work on it later.

**Comment by AlbyIanna** [comment]
@kittaakos please have a look at the last commit, I've created a separate contribution for the user fields.

**Review by per1234 — APPROVED** [review]
It is working perfectly for me.

Thanks Alberto!

File: arduino-ide-extension/src/browser/contributions/user-fields.ts [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+  }
+
+  private async showUserFieldsDialog(
+    key: string
+  ): Promise<BoardUserField[] | undefined> {
+    const cached = this.cachedUserFields.get(key);
+    // Deep clone the array of board fields to avoid editing the cached ones
+    this.userFieldsDialog.value = (
+      cached ?? (await this.boardsServiceProvider.selectedBoardUserFields())
+    ).map((f) => ({ ...f }));
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/user-fields.ts:83]: I do not understand this deep cloning part. Shouldn't IDE2 do the following?

```ts
    this.userFieldsDialog.value = cached
      ? cached.slice()
      : await this.boardsServiceProvider.selectedBoardUserFields();
```

File: arduino-ide-extension/src/browser/contributions/user-fields.ts [hunk 2]
```diff
@@ -0,0 +1,149 @@
...
+import { BoardsServiceProvider } from '../boards/boards-service-provider';
+import { UserFieldsDialog } from '../dialogs/user-fields/user-fields-dialog';
+import { ArduinoMenus, PlaceholderMenuNode } from '../menu/arduino-menus';
+import { MenuModelRegistry, Contribution } from './contribution';
+import { UploadSketch } from './upload-sketch';
+
+@injectable()
+export class UserFields extends Contribution {
+  private boardRequiresUserFields = false;
+  private userFieldsSet = false;
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/user-fields.ts:13]: Can we not simplify this and if there are user fields for an `fqbn` in the map, it means `true`. Otherwise, `false`.

File: arduino-ide-extension/src/browser/contributions/user-fields.ts [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+  private readonly cachedUserFields: Map<string, BoardUserField[]> = new Map();
+  private readonly menuActionsDisposables = new DisposableCollection();
+
+  @inject(UserFieldsDialog)
+  private readonly userFieldsDialog: UserFieldsDialog;
+
+  @inject(BoardsServiceProvider)
+  protected readonly boardsServiceProvider: BoardsServiceProvider;
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/user-fields.ts:21]: `private`

File: arduino-ide-extension/src/browser/contributions/user-fields.ts [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+    const { boardsConfig } = this.boardsServiceProvider;
+    const fqbn = boardsConfig.selectedBoard?.fqbn;
+    if (!fqbn) {
+      return '';
+    }
+    const address =
+      boardsConfig.selectedBoard?.port?.address ||
+      boardsConfig.selectedPort?.address;
+    if (!address) {
+      return '';
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/user-fields.ts:71]: Why not `undefined`?

File: arduino-ide-extension/src/browser/contributions/user-fields.ts [hunk 5]
```diff
@@ -0,0 +1,149 @@
...
+    if (!result) {
+      return;
+    }
+
+    this.userFieldsSet = true;
+    this.cachedUserFields.set(key, result);
+    return result;
+  }
+
+  async checkUserFieldsDialog(forceOpen: boolean): Promise<boolean> {
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/user-fields.ts:94]: A better API would use a default value. For example:

```ts
async checkUserFieldsDialog(forceOpen = false): Promise<boolean>
```

File: arduino-ide-extension/src/browser/contributions/user-fields.ts [hunk 6]
```diff
@@ -0,0 +1,149 @@
...
+  getUserFields(): BoardUserField[] {
+    return this.cachedUserFields.get(this.selectedFqbnAddress()) ?? [];
+  }
+
+  isRequired(): boolean {
+    return this.boardRequiresUserFields;
+  }
+
+  notifyFailedWithError(e: Error): void {
+    if (
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/user-fields.ts:141]: `CoreError.UploadFailed.is(e)` would be nicer than parsing the message of the error.

File: arduino-ide-extension/src/browser/contributions/upload-sketch.ts [hunk 7]
```diff
@@ -258,7 +163,7 @@ export class UploadSketch extends CoreServiceContribution {
     if (!CurrentSketch.isValid(sketch)) {
       return undefined;
     }
-    const userFields = this.userFields();
+    const userFields = this.userFields.getUserFields();
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/contributions/upload-sketch.ts:166]: Why not pass the `fqbn` from here?

**Review by kittaakos — COMMENTED** [review]
It's looking great. Thank you for the refactoring. I left a few remarks.

File: arduino-ide-extension/src/browser/contributions/user-fields.ts (hunk 1 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/contributions/user-fields.ts:83]: yes, your suggestion makes more sense to me. Thank you!

File: arduino-ide-extension/src/browser/contributions/upload-sketch.ts (hunk 7 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/contributions/upload-sketch.ts:166]: I don't see any reason since I can easily get them from the `boardsServiceProvider`. Passing it here would just add a parameter, with no benefit.

File: arduino-ide-extension/src/browser/contributions/user-fields.ts (hunk 2 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/contributions/user-fields.ts:13]: In that we would lose the value of the user field. As far as I know, we don't want that, we want to preserve the value, but give the user the possibility to change it.

File: arduino-ide-extension/src/browser/contributions/upload-sketch.ts (hunk 7 above)
Comment (kittaakos) [reply arduino-ide-extension/src/browser/contributions/upload-sketch.ts:166]: Exactly this; why do you want to calculate it twice? `verify`, and `upload` will require the `fqbn` anyway.

Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/contributions/upload-sketch.ts:166]: IMO how the user fields are stored is not related to the upload. I may want to open that dialog even if I'm not uploading.

**Review by kittaakos — APPROVED** [review]
Verified. Thank you!

https://user-images.githubusercontent.com/1405703/191059144-d62194b5-c1b6-49c7-a07f-b9fa70bacfff.mp4
