### PR TITLE
ATL-1136: Add .adoc and .md file support

### LINKED ISSUE #218: Assembly language file extension has the wrong case
**Describe the bug**
The Arduino build system requires assembly language files to use the `.S` file extension but the "New Tab" dialog only allows `.s`. Files using the `.s` extension are not compiled.

**To Reproduce**

1. Click the downward pointing triangle button on the right side of the tab bar.
2. Click "New Tab"
2. In the "Name for new file" dialog, type "Foo.S". - ".S is not a valid file extension." is shown and the "OK" button is disabled.

**Expected behavior**
The `.S` file extension to be allowed and the `.s` extension prohibited by the "New Tab" and  "Rename" dialogs of the tab control menu.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0.0-beta.3-nightly.20210313
Date: 2021-03-13T03:11:23.309Z
CLI Version: 0.16.1 alpha [76f55490]

**Additional context**
Reference from the Arduino Sketch Specification: https://arduino.github.io/arduino-cli/latest/sketch-specification/#additional-code-files

I believe the relevant code is here:
https://github.com/arduino/arduino-ide/blob/eadc9938547fdc42308d279b109f89c50474e6aa/arduino-ide-extension/src/common/protocol/sketches-service.ts#L89-L90

### PR DESCRIPTION
**Pull request by fstasi**
This PR  add support to create and view `.md` and `.adoc` files in IDE2. It also fix .S file extension (see #218 )

> Note: this PR alone do not solve the fact the IDE2 do not open automatically .md and .adoc files belonging to a sketch. That will be handled in a separate PR addressing [ATL-1152](https://arduino.atlassian.net/browse/ATL-1152)

## How to test
- open IDE2
- create a new tab using the top right button
- give it a name and and extension `.md` or `.adoc`

## Demo
doc-file-support

## Tasks
[ATL-1136](https://arduino.atlassian.net/browse/ATL-1136)
fixes #218

### CODE REVIEW

**Comment by kittaakos** [comment]
The CLI does not yet support these files, there is not much to review here.

File: arduino-ide-extension/src/common/protocol/sketches-service.ts [hunk 1]
```diff
@@ -88,7 +88,8 @@ export namespace Sketch {
         export const MAIN = ['.ino', '.pde'];
         export const SOURCE = ['.c', '.cpp', '.s'];
         export const ADDITIONAL = ['.h', '.c', '.hpp', '.hh', '.cpp', '.s', '.json'];
-        export const ALL = Array.from(new Set([...MAIN, ...SOURCE, ...ADDITIONAL]));
+        export const DOCUMENTATION = ['.md', '.adoc'];
```
Comment (kittaakos) [inline arduino-ide-extension/src/common/protocol/sketches-service.ts:91]: Please add them to _additional_. There is no _documentation_ category on the CLI. See [here](https://github.com/arduino/arduino-cli/blob/c4c723eb990accbd810ced70f7d14935dad831e1/arduino/globals/globals.go#L32-L42). [Here](https://github.com/arduino/arduino-cli/pull/1235) is the PR for the CLI. Thank you!

**Comment by kittaakos** [comment]
Could you please cover https://github.com/arduino/arduino-ide/issues/218 in this PR?

**Review by ubidefeo — APPROVED** [review]
I have tested also against #218 
LGTM
