### PR TITLE
Fix dialogs UI scalability

### LINKED ISSUE #1309: Improve styling of dialogs to avoid unwanted layout shift when scaling up the application
We've noted that the layouts of some dialogs in the IDE2 become distorted (with buttons going offscreen), when scaling up the application.

We should add css rules to ensure dialog layout shifts that impair usability do not occur on scaling up the app. Generally speaking our dialogs should have a fixed header and footer, content between should not overflow and push things out of view. 

We should review all dialogs at different scales in the IDE2, we can group simpler dialogs that share rules into single PR, and use separate PRs for more complex dialogs (like the board / port selector).

Example of distorted board selector dialog when app is scaled up and the window width is reduced:

### PR DESCRIPTION
**Pull request by AlbyIanna**
### Motivation
As explained in #1309, our dialogs might become distorted when scaling up the UI (from the settings or using the shortcut CMD/CTRL + '+').

I've made some fixes in order to make the interface readable and usable with an interface that is scaled up to 200%, with a minimum window size of 450px in width and 300px in height. Maybe they won't look beautiful, but every dialog should be at least usable and readable up to that size.

### Change description
Here's a list of screen captures **before** the changes, with an interface scale of 200% and a window size of 450x300:
#### Settings dialog
Screenshot 2022-08-09 at 09 32 25

#### IDE auto-update dialog
https://user-images.githubusercontent.com/6939054/183592585-33d4c0fc-93d3-44cf-8dae-5bcc9ae127b5.mov

#### Select Board dialog
https://user-images.githubusercontent.com/6939054/183593554-00628d68-d7df-4a25-9494-eb3cf80f0418.mov

#### WiFi 101/WiFi NINA Firmware Updater dialog
Screenshot 2022-08-09 at 09 46 08

#### Upload SSL Root Certificates
Screenshot 2022-08-09 at 09 48 34

---

And **after** the changes:
#### Settings dialog
https://user-images.githubusercontent.com/6939054/183591797-4a0e875a-82f1-4cde-ad15-66846996c6ed.mov

To avoid the '%' symbol unexpectedly going to a new line, I've added a `unitOfMeasure` prop to the settings-step-input component: a9ed5b570e7ecd318d79105e5a8bf3a87901dc32

#### IDE auto-update dialog
https://user-images.githubusercontent.com/6939054/183592629-2c28f4a6-c934-4a34-860c-f9c554107f17.mov

I needed to apply a major refactor on this dialog in order to move the buttons from the content of the dialog (which is the inner react component) to the footer (which is part of the `AbstractDialog` inherited from Theia): 553c6fe5eae242b7f40843402d61ab34bc1f8e50

#### Select Board dialog
https://user-images.githubusercontent.com/6939054/183593514-857ad34b-1397-44ad-9b15-476e2c795ecd.mov

Here I've decided to save some space when the size of the window is very small by adding a media query that removes the upper text paragraph on screen heights smaller than 400px: f8f07ea62be6d96191759c89da26c7fb5327c0fff8f07ea62be6d96191759c89da26c7fb5327c0ff

#### WiFi 101/WiFi NINA Firmware Updater dialog
Screenshot 2022-08-09 at 09 45 54

#### Upload SSL Root Certificates
https://user-images.githubusercontent.com/6939054/183594599-907318e6-ccaf-479d-8402-8ba138ab17cf.mov

### Other information
Fixes #1309 

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: arduino-ide-extension/src/common/protocol/ide-updater.ts [hunk 1]
```diff
@@ -2,6 +2,13 @@ import { JsonRpcServer } from '@theia/core/lib/common/messaging/proxy-factory';
 import { Event } from '@theia/core/lib/common/event';
 import { UpdateChannel } from '../../browser/arduino-preferences';
 
+export type UpdateProgress = {
+  progressInfo?: ProgressInfo | undefined;
+  downloadFinished?: boolean;
+  downloadStarted?: boolean;
+  error?: Error;
```
Comment (kittaakos) [inline arduino-ide-extension/src/common/protocol/ide-updater.ts:9]: I think `error` (type of `Error`) won't go through the wire via JSON-RPC as desired. It will be an empty object (`{}`). Probably we should try.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 2]
```diff
@@ -143,22 +116,118 @@ export class IDEUpdaterDialog extends AbstractDialog<UpdateInfo> {
...
+      this.controlPanel.removeChild(this.controlPanel.firstChild);
+    }
+    this.closeButton = undefined;
+  }
+
+  private appendNotNowButton(): void {
+    this.appendCloseButton(
+      nls.localize('arduino/ide-updater/notNowButton', 'Not now')
+    );
+    if(this.closeButton) {
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:134]: Please install [vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) in Code, and it will automatically format your code on save.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 3]
```diff
@@ -143,22 +116,118 @@ export class IDEUpdaterDialog extends AbstractDialog<UpdateInfo> {
...
+    this.addAction(
+      goToDownloadPageButton,
+      this.openDownloadPage.bind(this),
+      'click'
+    );
+    this.controlPanel.appendChild(goToDownloadPageButton);
+    goToDownloadPageButton.focus();
+  }
+
+  private openDownloadPage() {
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:195]: Although this is private, you can add the missing return type for consistency.

File: arduino-ide-extension/src/browser/style/ide-updater-dialog.css [hunk 4]
```diff
@@ -23,37 +23,49 @@
 .dialogContent.ide-updater-dialog
   .ide-updater-dialog--content
   .ide-updater-dialog--new-version-text.dialogSection {
-  margin-top: 0;
+    display: flex;
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/style/ide-updater-dialog.css:26]: Unexpected indentations in the CSS files.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 5]
```diff
@@ -143,22 +116,118 @@ export class IDEUpdaterDialog extends AbstractDialog<UpdateInfo> {
...
+    this.windowService.openNewWindow(DOWNLOAD_PAGE_URL, { external: true });
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:196]: If the `DOWNLOAD_PAGE_URL` is not used elsewhere, it's safer to have it as a string URL so that no magic can happen at runtime. This is a security consideration.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 6]
```diff
@@ -120,6 +63,18 @@ export class IDEUpdaterDialog extends AbstractDialog<UpdateInfo> {
   @inject(IDEUpdaterDialogWidget)
   protected readonly widget: IDEUpdaterDialogWidget;
 
+  @inject(IDEUpdater)
+  protected readonly updater: IDEUpdater;
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:67]: Can all these new fields be `private` and `readonly`?

**Review by kittaakos — COMMENTED** [review]
Thanks for taking the time and making the screencasts about the expected behavior. Very nice 👍

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx (hunk 5 above)
Comment (kittaakos) [reply arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:196]: Here is the electron recommendation: https://www.electronjs.org/docs/latest/tutorial/security#15-do-not-use-shellopenexternal-with-untrusted-content.

I know that the code you modified is not calling electron APIs, but I'd propose following their guidelines. What do you think?

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx (hunk 2 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:134]: I already have it installed, I don't know why it didn't work when I saved this one. Anyway, I'm fixing it, thanks.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx (hunk 5 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:196]: I never thought about it, thanks for this remark.

What I read on Electron documentation is:

>  When openExternal is used with untrusted content, it can be leveraged to execute arbitrary commands.

It mentions **untrusted content** to execute **arbitrary commands**, and the example refers to **user controlled data**. I'm not a security expert, but what I understand from the documentation is that using `openExternal` with a parameter that might change after some user action is risky. In this case, `DOWNLOAD_PAGE_URL` is a constant and it's not possible to change it at runtime, so there shouldn't be this risk, right?

File: arduino-ide-extension/src/common/protocol/ide-updater.ts (hunk 1 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/common/protocol/ide-updater.ts:9]: And anyway, this is not used in the backend, so I can move it away from `common`. Moving it.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx (hunk 5 above)
Comment (kittaakos) [reply arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:193]: > I never thought about it, thanks for this remark.

Me neither, until I read about this a few weeks ago.

> so there shouldn't be this risk, right?

It's up to you. The snippets with the `bad` and `good` examples from the electron docs are straightforward. If you have concerns, ask somebody from the security team for the final decision.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 7]
```diff
@@ -6,108 +6,49 @@ import { Widget } from '@theia/core/shared/@phosphor/widgets';
...
+    this._updateInfo = updateInfo;
+    this._updateProgress = {};
+    this.update();
   }
 
-  onDispose(): void {
-    if (this.downloadStarted && !this.downloadFinished)
-      this.updater.stopDownload();
+  setUpdateProgress(updateProgress: UpdateProgress): void {
+    this._updateProgress = updateProgress || {};
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:34]: Why do you need `updateProgress || {};` here? According to the types, `UpdateProgress` cannot be falsy here.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 8]
```diff
@@ -118,7 +59,19 @@ export class IDEUpdaterDialogProps extends DialogProps {}
...
+  private readonly updater: IDEUpdater;
+
+  @inject(IDEUpdaterClient)
+  private readonly updaterClient: IDEUpdaterClient;
+
+  @inject(LocalStorageService)
+  private readonly localStorageService: LocalStorageService;
+
+  @inject(WindowService)
+  private windowService: WindowService;
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:74]: `readonly` is still missing from here.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 9]
```diff
@@ -143,22 +113,118 @@ export class IDEUpdaterDialog extends AbstractDialog<UpdateInfo> {
...
-      this.widget.init(data, this.close.bind(this));
+      this.init();
+      this.widget.setUpdateInfo(data);
       return super.open();
     }
   }
 
   protected override onUpdateRequest(msg: Message): void {
     super.onUpdateRequest(msg);
-    this.widget.update();
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:161]: You can remove the entire overridden method if the internal `widget` does not require an update.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx (hunk 5 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:193]: Since the value is hard-coded, I believe it's pretty safe, so I wouldn't change it in this PR.

Also, we're doing something similar in [other](https://github.com/arduino/arduino-ide/blob/main/arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx#L142-L144) [places](https://github.com/arduino/arduino-ide/blob/main/arduino-ide-extension/src/browser/contributions/survey-notification.ts#L61-L64), so if we decide to apply your suggestion as a security practice, we should apply it across all the project.

Comment (kittaakos) [reply arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:193]: As you wish. 👍

**Comment by AlbyIanna** [comment]
I've put the PR back in draft because I've decreased the IDE version for testing purposes: https://github.com/arduino/arduino-ide/pull/1311/commits/26cbba6cd6ce3bdeda3f125729e203bbd8e67d00

**Review by 91volt — APPROVED** [review]

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx [hunk 10]
```diff
@@ -7,36 +6,32 @@ import ReactMarkdown from 'react-markdown';
...
   downloadStarted?: boolean;
-  progress?: ProgressInfo;
   error?: Error;
-  onDownload: () => void;
-  onClose: () => void;
-  onSkipVersion: () => void;
-  onCloseAndInstall: () => void;
+};
+
+export type IDEUpdaterComponentProps = {
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx:16]: [minor]: Why did you decide to use `type` instead of `interface` here?

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 11]
```diff
@@ -5,109 +5,49 @@ import { AbstractDialog } from '../../theia/dialogs/dialogs';
...
-    this.onClose();
+  setUpdateInfo(updateInfo: UpdateInfo): void {
+    this._updateInfo = updateInfo;
+    this.update();
   }
 
-  onDispose(): void {
-    if (this.downloadStarted && !this.downloadFinished)
-      this.updater.stopDownload();
+  setUpdateProgress(updateProgress: UpdateProgress): void {
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:32]: When using this API, I assume the method will *set* the update progress, but no. This will merge it. Please find a better name that describes the method. `updateProgress`, `mergeProgress`, etc.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 12]
```diff
@@ -130,10 +85,39 @@ export class IDEUpdaterDialog extends AbstractDialog<UpdateInfo> {
...
+    }
+    if (!this.onDownloadProgressChanged) {
+      this.onDownloadProgressChanged =
+        this.updaterClient.onDownloadProgressChanged((progressInfo) => {
+          this.widget.setUpdateProgress({ progressInfo });
+        });
+    }
+    if (!this.onDownloadFinished) {
+      // eslint-disable-next-line @typescript-eslint/no-unused-vars
+      this.onDownloadFinished = this.updaterClient.onDownloadFinished((_) => {
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:114]: You can use `this.onDownloadFinished = this.updaterClient.onDownloadFinished(() => {` and not `eslint-disable-*` is required.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx [hunk 13]
```diff
@@ -117,8 +57,23 @@ export class IDEUpdaterDialogProps extends DialogProps {}
 
 @injectable()
 export class IDEUpdaterDialog extends AbstractDialog<UpdateInfo> {
+  private onError: Disposable;
+  private onDownloadProgressChanged: Disposable;
+  onDownloadFinished: Disposable;
```
Comment (kittaakos) [inline arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:62]: missing `private` and how the (`Disposable`) fields are initialized is quite complicated.

Why not something like:

```ts
class IDEUpdaterDialog {

  constructor() {
  // current code
  }
  
  protected void postConstruct(): void {
    this.onError = ...;
    this.onDownloadFinished = ...;
    this.onDownloadProgressChanged = ...;
  }

  private init(): void {
  // current code without the if (!this.onError) and if (!this.onDownloadFinished), etc.
  }

 Maybe you can rename the `init` to `resetDownloadProgress,` or it's up to you. 


}
```

Please favor `onDid[Object]Did[Verb]` pattern: `onDownloadDidFinish`, `onDownloadProgressDidChange`.

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx (hunk 10 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx:16]: It's just habit, but for me, it's pretty much the same. Since across this project we typically use interfaces, I'll happily change it as you request, but can I ask you why you prefer it?

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx (hunk 13 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx:62]: It totally makes sense, all of it. Thanks for taking the time to make this kind of suggestions!

File: arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx (hunk 10 above)
Comment (kittaakos) [reply arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx:16]: > Interfaces are generally preferred over type literals because interfaces can be implemented, extended and merged.

From [here](https://github.com/bradzacher/eslint-plugin-typescript/blob/master/docs/rules/prefer-interface.md).

File: arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts [hunk 14]
```diff
@@ -453,7 +453,10 @@ export default new ContainerModule((bind, unbind, isBound, rebind) => {
   bind(BoardsConfigDialogWidget).toSelf().inSingletonScope();
   bind(BoardsConfigDialog).toSelf().inSingletonScope();
   bind(BoardsConfigDialogProps).toConstantValue({
-    title: nls.localize('arduino/common/selectBoard', 'Select Board'),
+    title: nls.localize(
+      'arduino/board/boardConfigDialogTitle',
+      'Select other board and port'
```
Comment (per1234) [inline arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts:458]:
```suggestion
      'Select Other Board and Port'
```

Unfortunately we not so organized as to have a style guide for such things, so the established conventions must serve in its place.

I did a survey of the dialog titles and it seems like the prevailing style for dialog titles is https://en.wikipedia.org/wiki/Title_case#Chicago_Manual_of_Style:

## Title case

- Additional Boards Manager URLs
- WiFi101 / WiFiNINA Firmware Updater
- Upload SSL Root Certificates
- Add File
- Board Info
- Software Update

CC: @91volt 

## Sentence case

- Save sketch folder as...
- Select a zip file containing the library you'd like to add

## Inconclusive

- Open
- Preferences
- Arduino IDE
  (the "About" dialog)

**Review by per1234 — CHANGES_REQUESTED** [review]

**Review by davegarthsimpson — APPROVED** [review]

File: arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts (hunk 14 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts:458]: Actually this change wasn't intentional. I'm changing it back, thanks for spotting it @per1234 ! (and sorry for the late reply 🙏)

Comment (AlbyIanna) [reply arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts:458]: EDIT: I mean, the intention was to change the title from "Select Board" to  "Select Other Board and Port" with the case you suggested.

Comment (per1234) [reply arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts]: I noticed the reworking you did of that dialog title and I think it is a very nice improvement even beyond the improved support for small window dimensions!

I end up having to describe the UI elements of the IDE in text quite often, which makes me especially conscious of the text labels such as dialog titles/headings.

**Review by per1234 — APPROVED** [review]
Very nice improvements Alberto!
