### PR TITLE
Use IPC message to focus on serial plotter window

### LINKED ISSUE #1346: Bring existing Serial Plotter window to foreground when selected from IDE UI
### Describe the request

If a **Serial Plotter** window is already open, bring it to the foreground when it is selected by either of the following user actions:

- Clicking the button on the Arduino IDE toolbar.
- Selecting **Tools > Serial Plotter** from the Arduino IDE menus.

🙂 The user actions will have an intuitive effect.

### Describe the current behavior

When it is opened, the Arduino IDE **Serial Plotter** appears in a dedicated window. While using the Serial plotter, the user is likely to switch back to the main Arduino IDE or other windows to adjust code, do research, etc. The Serial Plotter window will then be in the background, frequently either completely obscured by other windows or minimized, meaning it is really only visible as an item in the operating system task bar. They may forget Serial Plotter is already open and attempt to open it again via the Arduino IDE GUI, or perhaps just expect the selection to be a convenient way to bring it into visibility.

1. Select any port from the **Tools > Port** menu in the Arduino IDE.
1. Select **Tools > Serial Plotter** from the Arduino IDE menus.
   🙂 The Serial Plotter window opens in the foreground.
1. Select the main Arduino IDE window.
1. Select **Tools > Serial Plotter** from the Arduino IDE menus.
   😕 Nothing happens.
1. Click the Serial Plotter button on the Arduino IDE toolbar.
   😕 Nothing happens.

🙁 The lack of any effect of the user's action might give them the impression that something is wrong with the IDE.

### Arduino IDE version

2.0.0-rc9.2.snapshot-ca47e8a

### Operating system

Windows, Linux

### Operating system version

Windows 10, Ubuntu 20.04

### Additional context

The Arduino IDE 1.x **Serial Plotter** and **Serial Monitor** windows are brought to the foreground on selection via the GUI if they are already open.

---

Originally suggested at https://forum.arduino.cc/t/rc9-2-serial-monitor-send-button/1024938

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by AlbyIanna**
### Motivation
When serial plotter is already running, trying to open it again should bring the focus to the plotter window. Currently it's not working because running `window.focus()` raises the a cross-origin error:
```
Blocked a frame with origin "file://" from accessing a cross-origin frame
```

### Change description
Let the renderer send an IPC message to the backend, which in turn would show the serial plotter window.

### Other information
Fixes #1346

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: arduino-ide-extension/src/electron-main/theia/electron-main-application.ts [hunk 1]
```diff
@@ -325,12 +327,20 @@ export class ElectronMainApplication extends TheiaElectronMainApplication {
...
+
+          const showPlotterWindow = () => {
+            event.newGuest?.show();
+          };
+          ipcMain.on(SHOW_PLOTTER_WINDOW, showPlotterWindow);
           event.newGuest.setMenu(null);
           event.newGuest?.on('closed', () => {
-            electronWindow?.webContents.send('CLOSE_CHILD_WINDOW');
+            ipcMain.removeListener(SHOW_PLOTTER_WINDOW, showPlotterWindow);
+            electronWindow?.webContents.send(CLOSE_PLOTTER_WINDOW);
```
Comment (kittaakos) [inline arduino-ide-extension/src/electron-main/theia/electron-main-application.ts:343]: Can you explain why it needs to be `electronWindow?.webContents` instead of `electronWindow.webContents`? The same applies to all `event.newGuest?.x`.

File: arduino-ide-extension/src/electron-main/theia/electron-main-application.ts [hunk 2]
```diff
@@ -23,8 +23,10 @@ import * as os from '@theia/core/lib/common/os';
 import { Restart } from '@theia/core/lib/electron-common/messaging/electron-messages';
 import { TheiaBrowserWindowOptions } from '@theia/core/lib/electron-main/theia-electron-window';
 import { IsTempSketch } from '../../node/is-temp-sketch';
+import { CLOSE_PLOTTER_WINDOW, SHOW_PLOTTER_WINDOW } from '../../common/ipc-communication';
 
 app.commandLine.appendSwitch('disable-http-cache');
+app.commandLine.appendSwitch('disable-site-isolation-trials');
```
Comment (kittaakos) [inline arduino-ide-extension/src/electron-main/theia/electron-main-application.ts:29]: Why is it needed?

File: arduino-ide-extension/src/electron-main/theia/electron-main-application.ts [hunk 3]
```diff
@@ -325,12 +327,20 @@ export class ElectronMainApplication extends TheiaElectronMainApplication {
               devTools: true,
               nativeWindowOpen: true,
               openerId: electronWindow?.webContents.id,
+              webSecurity: false,
```
Comment (kittaakos) [inline arduino-ide-extension/src/electron-main/theia/electron-main-application.ts:330]: Why `false`? Theia [does not set it to `false`](https://github.com/eclipse-theia/theia/blob/9ab46186f1f4db52b1a4dc42342e43b8c1606aba/packages/core/src/electron-main/electron-main-application.ts#L293-L301). Hence, it's `true` by default.

File: arduino-ide-extension/src/electron-main/theia/electron-main-application.ts (hunk 2 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/electron-main/theia/electron-main-application.ts:29]: My bad, this was a leftover from a previous solution 🙏

File: arduino-ide-extension/src/electron-main/theia/electron-main-application.ts (hunk 3 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/electron-main/theia/electron-main-application.ts:330]: also this one

File: arduino-ide-extension/src/electron-main/theia/electron-main-application.ts (hunk 1 above)
Comment (AlbyIanna) [reply arduino-ide-extension/src/electron-main/theia/electron-main-application.ts:343]: Actually it's not needed, apart from here: https://github.com/arduino/arduino-ide/blob/2e3c5dee4bd1937731171a5b986110fa6eacce47/arduino-ide-extension/src/electron-main/theia/electron-main-application.ts#L337

I'm changing them, thanks!
