### PR TITLE
Remove gRPC error code from error notifications

### LINKED ISSUE #151: "Compilation error: Error: 2 UNKNOWN: exit status 1" error message is unnecessarily cryptic
**Describe the bug**
Any program I run and attempt to compile I get this error:

> c:/users/anton/appdata/local/arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/../lib/gcc/avr/7.3.0/../../../../avr/lib/avr5/crtatmega328p.o:(.init9+0x0): undefined reference to `main'
collect2.exe: error: ld returned 1 exit status
Compilation error: Error: 2 UNKNOWN: exit status 1

- I recently got the beta and no matter what I do I had this (yes I restarted my pc) and I even download the latest Git (2.30.1) 64-bit.

**To Reproduce**

1. Open any code
2. Click compile

**Expected behavior**
Expected for the code to compile.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Version: 2.0.0-beta3

**Additional context**
This could be due to from when some notification occurred which I couldn't figure out what it was for. I do remember that it led to [this link](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc). However, I don't see this notification anymore?

### PR DESCRIPTION
**Pull request by silvanocerza**
Compilation error before:
image

Upload error before:
image

Compilation error after: 
image

Upload error after:
image

Fixes #151.

### CODE REVIEW

File: arduino-ide-extension/src/node/core-service-impl.ts [hunk 1]
```diff
@@ -227,11 +229,12 @@ export class CoreServiceImpl extends CoreClientAware implements CoreService {
         result.on('end', () => resolve());
       });
     } catch (e) {
+      const errorMessage = `Error while burning the bootloader: ${e.details}`;
```
Comment (fstasi) [inline arduino-ide-extension/src/node/core-service-impl.ts:232]: I know errors are not localized (yet)... but they should.. 

Maybe we can start adopting i18n for new errors

**Review by fstasi — APPROVED** [review]

File: arduino-ide-extension/src/node/core-service-impl.ts (hunk 1 above)
Comment (fstasi) [reply arduino-ide-extension/src/node/core-service-impl.ts:232]: @silvanocerza btw the PR is good. 🪄
